### ISSUE TITLE
ergoCub 1.0 S/N:000 –  not finishing calibration correctly

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-tech-support#1637] opened 2023-09-11 13:50 UTC
### Robot Name 🤖

None

### Request/Failure description

When starting the robot, the robot does not finish the calibration sequence and throws the following error in the log, which I am not sure how to interpret.

```
	40,564850	ERROR			 from BOARD 10.0.1.22 (right_arm-eb22-j7_10), src LOCAL, adr 0, time 113s 762m 671u: (code 0x00000013, par16 0x0002 par64 0x0000000000000000) -> SYS: the EOtheInfoDispatcher could not accept a eOmn_info_properties_t item inside its transmitting queue. In par16 there is the number of lost items. +
```

At the end, i tried to capture a video but the robot in the third time restarted correctly.
I am opening this issue in case the problem occurs again 

### Detailed context

The output of the log is the following one
[Uploading log_ergocub-torso_yarprobotinterface_2030.txt…]()

**Comment by AntonioConsilvio** [comment] 2023-09-14 09:15
Hi @mebbaid, I am quite sure that the problem was due this [issue](https://github.com/robotology/icub-tech-support/issues/1632#issuecomment-1711787645), where I fixed the electronical problems (see the [comment](https://github.com/robotology/icub-tech-support/issues/1632#issuecomment-1719057814)).

So give us feedback if the problem is still there or not.

cc @sgiraz

**Comment by mebbaid** [comment] 2023-09-15 10:12
The issue did not occur again.

**Comment by sgiraz** [comment] 2023-09-15 12:33
> https://github.com/robotology/icub-tech-support/issues/1637#issuecomment-1721025030

Nice! Closing.

**Closed by sgiraz** 2023-09-15 12:33 UTC
Labels: ergoCub 1.0 S/N:000
