### ISSUE TITLE
iCubShanghai01 – JOINT 6(I_wrist_yaw) - HARDWARE FAULT

### ISSUE THREAD

**Issue by jimingda** [robotology/icub-tech-support#1573] opened 2023-06-06 10:28 UTC
### Device name 🤖

iCubShanghai01

### Request/Failure description

The message on the yarpmotorgui about left_arm is as below:

```
JOINT 6(i_wrist_yaw)-HARDWARE FAULT
Fault Code: 16
FaultMessage: hard limit reached. The joint position is outside its hardware boundaries. par16 = ID

Encoder: 45.434 deg
```

How do i fix this fault?

Regards
![joint6hardfault](https://github.com/robotology/icub-tech-support/assets/7019692/da89af88-a203-4f69-bd56-332124dfc46c)

### Detailed context

None

**Comment by jimingda** [comment] 2023-06-07 01:54
Actually today when i turn on icub, and launch yarprobotinterface again, the left arm go back to normal again as well as the joint 6.
All the status of joints on yarpmotorgui is green now.

**Comment by sgiraz** [comment] 2023-06-16 11:26
I guess the problem is gone, hence I'm going to close this issue.
Feel free to reopen in necessary.

**Closed by sgiraz** 2023-06-16 11:26 UTC
Labels: iCubShanghai01
