### ISSUE TITLE
ergoCub 1.1 S/N:001 – Connector of ethernet cable robot side broken

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1944] opened 2024-10-22 14:10 UTC
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

As per the title

cc @Gandoo @Fabrizio69 

### Detailed context

As per the title

**Comment by AntonioConsilvio** [comment] 2024-10-22 14:21
maybe related with: 

- https://github.com/robotology/icub-tech-support/issues/1921

**Comment by Gandoo** [comment] 2024-10-23 06:26
ciao @isorrentino and @AntonioConsilvio I replaced the RJ45 connector, but the problem is on the FED card which has a broken network connector.
You have to remove the back to replace the board

![Image](https://github.com/user-attachments/assets/76b9a7fa-eda8-42aa-af26-d95257808cb3)

cc @S-Dafarra @Fabrizio69

**Comment by Gandoo** [comment] 2024-10-25 13:14
ciao @isorrentino and @AntonioConsilvio I managed to replace the FED board now the network connector remains inserted

![Image](https://github.com/user-attachments/assets/9af25ac2-7bfa-4904-872d-a46afccc93f1)

cc @Fabrizio69

**Comment by AntonioConsilvio** [comment] 2024-10-29 21:57
Good job @Gandoo, closing! 🚀

**Closed by AntonioConsilvio** 2024-10-29 21:57 UTC
Labels: ergoCub 1.1 S/N:001
