### ISSUE TITLE
DNS not working on icub server?

### ISSUE THREAD

**Issue by matejhof** [robotology/icub-tech-support#1146] opened 2021-06-17 12:42 UTC
### Device name 🤖

iCubPrague01

### Request/Failure description

We received the iCub setup this week and connected the server to the switch and the `icub-laptop`, `icub-head`, and `icub-cuda` to the switch. We run yarpserver on the `icub-laptop`.
The `icub-laptop` and the `icub-head` can ping each other. The `icub-cuda` cannot be pinged and cannot ping the others. Only when IP addresses are used, this is possible. 
It seems that the DNS server configured on icub-server is able to resolve just the icub-head and no other computers are being resolved. Tested with nslookup (server 10.0.0.1)
Also, when adding a new laptop to the switch, we cannot `yarp detect` without manually changing ip address in yarp config.
My colleagues @0xBEDA, @rozliv , @rustlluk may have more information.

### Detailed context

![Screenshot from 2021-06-17 14-35-20](https://user-images.githubusercontent.com/6461061/122398397-22b24400-cf7a-11eb-9f73-1283084f42b1.png)

**Comment by maggia80** [comment] 2021-06-17 12:47
cc @mbrunettini

**Comment by mbrunettini** [comment] 2021-06-17 13:38
Can you confirm that 
1. the ethernet connection scheme (as described in the document shipped with the robot) has been followed in any step?
2. The setup was powered on following the startup procedure as described in the document shipped with the robot?

It seems that the DNS is not working and the most common root cause is when the` icub-server` is starting when the switch is not read and/or it's not connected properly

**Comment by rustlluk** [comment] 2021-06-18 08:24
I have double-checked all the cables and did the whole turning-on procedure again. Now `yarp detect` on connected laptops can properly find the `yarpserver` running on `icub-laptop`. However, the DNS server still knows only `icub-head` and `icub-srv`. But that's something we can probably fix by ourselves. I am just wondering what is the "best practice" used with _yarp_? Is it better to set names like `icub-laptop, icub-cuda` with DNS or to use IP addresses?

**Comment by mbrunettini** [comment] 2021-06-18 08:38
The DNS is configured to resolv both `icub-laptop` and `icub-cuda` in the same way, so I don't think the issue is on the DNS server saide.
Can you please do the following on `icub-head`
```
ping icub-laptop
ping icub-cuda
```

(of course both machines must be ON and connected with an **ethernet** cable to the `icub-switch`)

And post here the results? Thanks

The _best practice_ for you setup is to use the hostnames, BUT you can use IP as well because:
- `icub-head` has a fixed IP
- `icub-laptop` and `icub-cuda` has DHCP assigned IP, but with a reservation, so if yuo connect the with a cable they always get the same IP

The advantage in using _hostnames_ is that (if everything works correctly) you can always add another machine to the setup adn it will be reachable with its hostname, so you don't have to deal with IP. Plus, if you need to take `icub-latop` or `icub-cuda` OUT the setup (for any reason) it's already configured with the DHCP, which is the most common solution.

**Comment by rustlluk** [comment] 2021-06-18 08:47
Ok, great. Thanks for the info. Here the screens:
![cuda](https://user-images.githubusercontent.com/54062527/122534120-82fcc080-d022-11eb-8813-087044b04c1d.png)
![laptop](https://user-images.githubusercontent.com/54062527/122534125-842ded80-d022-11eb-9777-db502e0d04d5.png)

**Comment by mbrunettini** [comment] 2021-06-18 08:49
Thanks, but 

> Can you please do the following on icub-head



>

**Comment by rustlluk** [comment] 2021-06-18 09:02
I am sorry, my bad. I somehow read it incorrectly
![Screenshot from 2021-06-18 11-00-50](https://user-images.githubusercontent.com/54062527/122536160-898c3780-d024-11eb-8c7f-52d34a4645bd.png)

**Comment by mbrunettini** [comment] 2021-06-18 09:43
Fine, now have to check the `icub-sever` : please ssh to `icub-server` (10.0.0.1) and issue the following commands
```
sudo systemctl status bind9
dhcp-lease-list
tar cvf /home/icub/named_log.tar /var/log/named/
```

and the please post here the results as well as the file `/home/icub/named_log.tar` created by the last command

Thanks!

**Comment by rustlluk** [comment] 2021-06-18 09:55
`Rustli-ubuntu` is my laptop (connect with Ethernet to switch), which is btw pingable from both `icub-laptop, icub-cuda`. 
![Screenshot from 2021-06-18 11-50-49](https://user-images.githubusercontent.com/54062527/122543025-a0825800-d02b-11eb-982d-5ec37feaab7d.png)
[named_log.zip](https://github.com/robotology/icub-tech-support/files/6676220/named_log.zip)
*Github didn't let me upload tar, so you have it as zip

**Comment by mbrunettini** [comment] 2021-06-18 11:36
Apparently the DNS service is working correctly, though. This is also confirmed by the fact that you laptop is resolved by `icub-laptop `and  `icub-cuda`
I think this deserves a live debugging session, maybe we should arrange a call with the help of @violadelbono or @Uboldi80 .

Meanwhile, it can be useful to know:

1. (while connected to the `icub-switch`) from `Rustli-ubuntu` the output of `ping google.com`
2. (same as above) from `icub-laptop` the output of `ping google.com`
3. (same as above) the ip address of  `icub-laptop` (eg. with the output of `ip addr`)

Thanks again.

**Comment by rustlluk** [comment] 2021-06-18 12:48
Pinging Google gives the same output on both machines
![google](https://user-images.githubusercontent.com/54062527/122559403-910d0a00-d03f-11eb-9054-e70818cf1061.png)
IP address is 10.0.0.111 (corresponds to the label on USB-Eth adapter)
![eth](https://user-images.githubusercontent.com/54062527/122559434-9c603580-d03f-11eb-9866-b62021bae896.png)

I tried to plug ethernet on `icub-laptop` directly to the laptop and it successfully obtains IP from DHCP -- a different MAC address than the USB adapter, so the static reservation does not get activated. It made me try to disable the reservation of both laptops in `/etc/dhcp/dhcpd.conf` on `icub-srv`, which made both laptops resolved by DNS. But after enabling the reservation again the old problem arises.  

Is it important to have the static reservation for the laptops (they even get the right addresses without reservation, but I am not sure if it's a permanent thing or just some temporary result from the previous reservation)? If the reservation is needed and you would like to do the live debugging, I am up for it.

Thanks!

**Comment by mbrunettini** [comment] 2021-06-18 13:00
Please **always** use the USB adapter on the icub-laptop, as written in both documentation and on the laptop itself.

the reservation is important because _at the moment_ robot-bazaar does not support hostnames (but we are working to fix it), so we reserved  IPs, so they can be used with robot-bazaar.

**Comment by mbrunettini** [comment] 2021-06-18 14:22
On `icub-server`, can you please 
1. backup the file `/etc/dhcp/dhcpd.conf` with
```
sudo cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.orig
```
2. edit the file
 `/etc/dhcp/dhcpd.conf`
by replacing the following line
```
#allow client-updates;
```
with
```
allow client-updates;
update-static-leases true;
```

(i.e. you should uncomment the line `update-static-leases true;` and add the line `update-static-leases true;` )

and the restart the dhcpd service with
```
sudo systemctl restart isc-dhcp-server
```

And let us know, thanks!

**Comment by rustlluk** [comment] 2021-06-18 14:58
It seems to fix the issue, both laptops are now pingable and `nslookup` knows the names even when the devices are offline. 

I think we can close the issue.  @matejhof 

Thanks a lot!

**Closed** 2021-06-18 15:11 UTC
Labels: iCubPrague01
