### ISSUE TITLE
Left arm wrist broken 

### ISSUE THREAD

**Issue by lunagava** [robotology/icub-tech-support#989] opened 2020-09-22 15:30 UTC
## Brief description of the request/failure
Wrist yaw joint doesn't respond'  because wrist motor of left arm is broken. 
## Detailed context
Probably it happened because the hand put pressure on the air hockey table while iCub was grasping the paddle, even if I put limits on z direction. I'm very sorry about that. 

## Accompanying material

![IMG_5453](https://user-images.githubusercontent.com/45895918/93902884-5f595380-fcf8-11ea-8de7-b23790de0a4a.jpg)

**Comment by julijenv** [comment] 2020-09-28 14:05
dear @lunagava ,
the motor of the wrist is broken, it will be repaired next week

**Comment by lrapetti** [comment] 2020-10-16 08:44
The problem is still there right?

I am asking because I have been using the robot without running wrist and fingers, and when I tested the whole-robot after my tests I have noticed the left wrist yaw seems to be still broken.

**Comment by DanielePucci** [comment] 2020-10-16 08:54
CC @julijenv @violadelbono

**Comment by violadelbono** [comment] 2020-10-16 08:58
Yes we didn't have time to fix it yet 😢

**Comment by lrapetti** [comment] 2020-10-16 09:07
> Yes we didn't have time to fix it yet 😢

No worries, I was just worried we broke it again :grimacing:
(we are currently running the robot without the wrist exactly to avoid that)

**Comment by GiacomoVassallo13** [comment] 2020-11-16 10:28
The crankshaft of the motor is broken into two parts, one of which is stuck in the pulley.
I try to extract it in the workshop, but I point out that this pulley has the hole that is visibly not aligned.
![20201116_111420 1206](https://user-images.githubusercontent.com/70649516/99241887-bbbf8780-27fe-11eb-8d7d-b04629f8c6d5.jpg)
![20201116_111323 1205](https://user-images.githubusercontent.com/70649516/99241941-ce39c100-27fe-11eb-96a8-ec2a2e4d53f4.jpg)

**Comment by GiacomoVassallo13** [comment] 2020-11-16 10:44
take the last motor (IIT cod. 4471) to the warehouse.
![20201116_113608 1207](https://user-images.githubusercontent.com/70649516/99243533-1bb72d80-2801-11eb-9d12-e13321d39470.jpg)

**Comment by GiacomoVassallo13** [comment] 2020-11-16 12:01
The pulley must be replaced , it must be replaced by taking the mechanical part from another kit, I await instructions on thisbecause it was not possible to recover it due to the deformation of the hole which led it to have a diameter of the hole for housing the shaft more fat already diameter of one millimeter.
the part number is RC_TLR_010_P_036
It must be replaced by taking the mechanical part from another kit, I await instructions on this
![20201116_124757 1208](https://user-images.githubusercontent.com/70649516/99250123-79507780-280b-11eb-9c8a-c157c84cb02d.jpg)

**Comment by GiacomoVassallo13** [comment] 2020-11-17 11:54
the broken motor was replaced with a working one and tested .
![1605613860994-571887437 1220](https://user-images.githubusercontent.com/70649516/99387258-f6dfba80-28d3-11eb-9679-e07a77bdcbbe.jpg)

**Comment by GiacomoVassallo13** [comment] 2020-11-17 12:00
I noticed that the prosimal of the thumb needs to be rewired, I arrange it before reassembling the hand.
![20201117_125532 1221](https://user-images.githubusercontent.com/70649516/99387760-d2d0a900-28d4-11eb-926a-a2ac0b0000bd.jpg)

**Comment by violadelbono** [comment] 2020-11-18 08:57
After replacing the motor, the left arm was re-activated and now the robot is fixed.

I close the issue 🥳

**Closed** 2020-11-18 09:01 UTC
Labels: iCubGenova02
