### ISSUE TITLE
ergoCub 1.1 S/N:001 – yarprobotinterface unable to connect to leg boards eb6, eb7, eb8, eb9

### ISSUE THREAD

**Issue by G-Cervettini** [robotology/icub-tech-support#1786] opened 2024-03-27 17:56 UTC
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The yarprobotinterface has been restarted after a minor fall while walking through the WalkingModule to ensure that the calibration was still correct. After restarting this module we were no longer able to connect to some of the control boards in the legs:  

```
[ERROR] theNVmanager::Impl::ask() had a timeout for BOARD right_leg-eb6-j0_3 IP 10.0.1.6 and nv ID32 = 0x00000002 -> IND = 0, TAG = eoprot_tag_mn_comm_status_managementprotocolversion
[ERROR] theNVmanager::Impl::ask() had a timeout for BOARD right_leg-eb7-j4_5 IP 10.0.1.7 and nv ID32 = 0x00000002 -> IND = 0, TAG = eoprot_tag_mn_comm_status_managementprotocolversion
[ERROR] theNVmanager::Impl::ask() had a timeout for BOARD left_leg-eb8-j0_3 IP 10.0.1.8 and nv ID32 = 0x00000002 -> IND = 0, TAG = eoprot_tag_mn_comm_status_managementprotocolversion
[ERROR] theNVmanager::Impl::ask() had a timeout for BOARD left_leg-eb9-j4_5 IP 10.0.1.9 and nv ID32 = 0x00000002 -> IND = 0, TAG = eoprot_tag_mn_comm_status_managementprotocolversion
```

### Detailed context

Most likely the **E5** cable got damaged/detached during the fall.  

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/101020439/7ed53b67-17cb-4c77-8af8-1cb6760316e0)  

I tried to run the `FirmwareUpdater` and run a `discover`, this confirmed that the boards from 10.0.1.6 to 10.0.1.9 are not reachable:  
![Screenshot from 2024-03-27 18-50-49](https://github.com/robotology/icub-tech-support/assets/101020439/b81f3dda-0300-48e0-88bd-8bc5c240df18)

### Additional context

[log_ergocub-torso_yarprobotinterface_1251.zip](https://github.com/robotology/icub-tech-support/files/14779302/log_ergocub-torso_yarprobotinterface_1251.zip)

### How does it affect you?

I wasn't able to finish my walking experiments.

**Comment by AntonioConsilvio** [comment] 2024-03-28 08:25
Hi @G-Cervettini, the problem was caused by the E5 cable on the side connected to the EB6 board (Right_leg). The crimps were coming out of the connector:
![IMG_20240328_084757](https://github.com/robotology/icub-tech-support/assets/114915464/135bc0dd-3540-4d3b-a9ff-8afcaed70ece)


I reinserted the crimps and fixed the connector so that the crimps would not come out, and then I put glue so that the crimps would stay in place.

The robot was tested together with @GiulioRomualdi and it works properly! 

Closing!✅

**Closed by AntonioConsilvio** 2024-03-28 08:25 UTC
Labels: ergoCub 1.1 S/N:001
