### ISSUE TITLE
ergoCub 1.1 S/N:001 – Right hip pitch joint jumped loosing the calibration

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1732] opened 2024-01-30 14:57 UTC
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

While having the robot on the ground one of the joints of the right hip pitch encoder had a jump, moving to a new position. After this jump, the same encoder values for the two legs, result in a different physical configuration.

Plot here:

![image](https://github.com/robotology/icub-tech-support/assets/43743081/d87775fe-907b-481c-81dc-13c22b9b57c6)

### Detailed context

Photos here:

![MicrosoftTeams-image](https://github.com/robotology/icub-tech-support/assets/43743081/8d1e4420-b01c-413f-b0c3-07c5218d3602)
![MicrosoftTeams-image(2)](https://github.com/robotology/icub-tech-support/assets/43743081/cd475389-ab9c-43c4-bc46-0b21407a77b7)
![MicrosoftTeams-image(1)](https://github.com/robotology/icub-tech-support/assets/43743081/a4192d07-f98c-4dfa-8069-67e2ae2bcc11)
![MicrosoftTeams-image(3)](https://github.com/robotology/icub-tech-support/assets/43743081/ef367c02-f4c1-48e5-a4b5-34071ce2bbba)

cc @DanielePucci @maggia80 @GiulioRomualdi

**Comment by DanielePucci** [comment] 2024-01-30 15:44
We hoped that the jump was due to the AMO, but actually @isorrentino checked and we already using the LCORE. So, it seems that the problems are due to the LCORE measurements. Then, with @GiulioRomualdi, we re-enabled the AMO and we tested the walking **that started vibrating much more**. 

Clearly, if there is a problem in the LCORE, the field oriented control is going to be problematic.

@isorrentino suggested that the LCORE might be dirty: could this be the case @sgiraz @AntonioConsilvio @Fabrizio69 ?

**Comment by sgiraz** [comment] 2024-01-31 08:39
> Clearly, if there is a problem in the LCORE, the field oriented control is going to be problematic.

cc @ale-git @valegagge

**Comment by sgiraz** [comment] 2024-01-31 10:03
@ale-git, @AntonioConsilvio and I discussed F2F about the LCORE problem.

It is possible to decrease the tolerance in https://github.com/robotology/robots-configuration/blob/08f2a6ecc3c9d4cc2dad6b4524775b9f8f97e9a2/ergoCubSN001/hardware/motorControl/right_leg-eb6-j0_3-mc_service.xml#L51 to `2.1` (the minimum value) to see if a "dirty encoder" warning is detected.

We'll give it a try asap.

**Comment by AntonioConsilvio** [comment] 2024-02-05 15:32
Hi! The AMO cable has been fixed in this [issue](https://github.com/robotology/icub-tech-support/issues/1742):

It could be that the problem described in this issue was caused by abnormal behaviour of the AMO.
So, I would ask for feedback if the problem has happened again.

Thank you!

cc @isorrentino @GiulioRomualdi

**Comment by AntonioConsilvio** [comment] 2024-02-14 15:29
Since the robot completed the Farnesina's Demo successfully, without showing this problem anymore, I think that we can close this issue!

cc @isorrentino

**Closed by AntonioConsilvio** 2024-02-14 15:29 UTC
Labels: ergoCub 1.1 S/N:001
