### ISSUE TITLE
Right arm shoulder tendon broke

### ISSUE THREAD

**Issue by rozliv** [robotology/icub-tech-support#1483] opened 2023-01-09 17:08 UTC
### Device name 🤖

iCubPrague01

### Request/Failure description

The right arm shoulder tendon broke. @matejhof @0xBEDA

### Detailed context

While testing new arm movements, the right arm shoulder tendon broke.
![IMG_1941](https://user-images.githubusercontent.com/45361823/211366003-ec51f0c6-7e47-4d7b-857a-5385f99c4a64.jpg)

**Comment by matejhof** [comment] 2023-01-10 09:33
hi @GiacomoVassallo13, we are on a tight schedule for a deadline and we need to run experiments. Our iCub purchase contract includes a maintenance plan for 3 years after warranty, which includes consumables (tendons, wires, crimps...). Could you please send us the tendon (or even better some extra ones) as soon as possible? Then we can maybe  organize a video call and you would explain to us how to change it? Thank you!

**Comment by Fabrizio69** [comment] 2023-01-11 11:07
Hi @matejhof, we are working to send you a spare shoulder set.

**Comment by matejhof** [comment] 2023-01-12 12:13
Thanks! 
While the set is on the way, can you please point us to instructions how to change it? Is there a tutorial? Or is it better to schedule a call with you and do it online under your supervision?   @0xBEDA will be in charge on our side.
@Fabrizio69 @GiacomoVassallo13

**Comment by pattacini** [comment] 2023-01-12 12:17
Hi @matejhof 

>While the set is on the way, can you please point us to instructions how to change it? Is there a tutorial?

In the meantime, you can peruse some resources at https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/.

**Comment by rozliv** [comment] 2023-01-18 13:36
We received tendons today. Now we are trying to replace them. We are stuck at replacing cables 1 and 2 together. We removed/loosed cables 5-8. The tendons seem to be too short when pulling them on the pulleys. While turning pulleys, the missing length varies from 3 to 20 mm. @Fabrizio69 @AntonioConsilvio @GiacomoVassallo13

**Comment by AntonioConsilvio** [comment] 2023-01-18 14:15
Hi @rozliv @matejhof , are you sure you put the right cable in the right place, following the right path around the pulleys?

Also, you should loosen the cable turnbuckles if you haven't already done so and keep the pulleys in the same position that you can see in the guide (https://icub-tech-iit.github.io/documentation/icub_tendons/shoulder_elbow/#41-right-shoulder-rotation-cable-1-and-2).  

It is difficult to understand and explain by message, so if you need more support you can definitely write to us; but if the problem cannot be solved, we can schedule a video call to provide better support.

Anyway keep writing to us if you need more suggestions.

cc @Fabrizio69 @GiacomoVassallo13

**Comment by matejhof** [comment] 2023-01-18 14:25
Hi! We suggest to schedule the video call - that seems like the most efficient solution. When would you be available? Thanks! @AntonioConsilvio @GiacomoVassallo13
 cc @Fabrizio69 @0xBEDA @rozliv

**Comment by rozliv** [comment] 2023-01-18 15:03
Here is a photo - the cable 2 is too short. ![image](https://user-images.githubusercontent.com/45361823/213206025-9b96c27b-d34b-488d-9c20-7159bc42993f.jpeg)

**Comment by AntonioConsilvio** [comment] 2023-01-18 15:09
@rozliv Maybe try to rotate the pulleys so that they are exactly as in the picture.
![image](https://user-images.githubusercontent.com/114915464/213207235-a7ef034b-2241-4bec-9f34-679f6269fdbe.png)

**Comment by AntonioConsilvio** [comment] 2023-01-18 15:18
@rozliv To rotate this pulley, remove these two screws.
![Inked213206025-9b96c27b-d34b-488d-9c20-7159bc42993f](https://user-images.githubusercontent.com/114915464/213209410-bb52ab3e-82eb-4c97-aecd-149ea0ea6120.jpg)

And if you have a pliers like this:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/114915464/213209934-4fc1135b-3aa7-4457-91dc-2a374bae687b.png)

You can insert it into the two holes and rotate the pulley.

**Comment by rozliv** [comment] 2023-01-18 15:25
Those screws are not the original ones, we use them to rotate the pulley.

**Comment by AntonioConsilvio** [comment] 2023-01-18 15:29
Are the cable tensioners as loose as possible? @rozliv 
![InkedCattura](https://user-images.githubusercontent.com/114915464/213212953-b7a4b319-1817-4926-a557-ee7f4d18e143.jpg)

**Comment by rozliv** [comment] 2023-01-18 15:30
Do tensioners for cables 3 and 4 need to be loosened as well?

**Comment by AntonioConsilvio** [comment] 2023-01-18 15:49
Perhaps it is too difficult to explain by message, so I propose to schedule a video call on Monday, Feb. 23, at 10 a.m. to clarify the situation (if you are available).
@matejhof @rozliv 

cc @Fabrizio69 @GiacomoVassallo13

**Comment by AntonioConsilvio** [comment] 2023-01-18 16:18
@rozliv Yes, Tuesday we are available, I propose 10 a.m. if that's okay with you. 

Anyway you can try loosening cables 3 and 4, but I think in this situation it shouldn't help. Also because if it would help, it should be written in the guide.

cc @Fabrizio69 @GiacomoVassallo13

**Comment by AntonioConsilvio** [comment] 2023-01-18 16:37
> Tuesday at 11 is better for us. @AntonioConsilvio

Okay, that's fine for us too.

**Comment by rozliv** [comment] 2023-01-24 13:44
We tried to run the robot but we cannot move the shoulder forward (see the photo)
![image](https://user-images.githubusercontent.com/45361823/214310498-d63fe1b0-22e3-4267-bfd2-41c88c07a1ab.jpeg)

@Fabrizio69 @AntonioConsilvio

**Comment by AntonioConsilvio** [comment] 2023-01-24 14:48
@rozliv, the joint that doesn't work is the joint 0. The joint 0 is a motor that moves all pulleys. because:


![Image](https://user-images.githubusercontent.com/114915464/214320038-208f71ad-4c5b-4455-bea1-03417bc9af37.jpg)

As you can see in the photo above,  joint 0 hasn't a cable, there is a pin that moves other joints and therefore all the cables in the shoulder accordingly. 
So, if it cannot move, it means that (if the problem is mechanical) there is one of the other pulleys, where the cables turn, that is blocking the motor of joint 0.

So provide us with many pictures, from multiple viewpoints, of all the cable windings, especially this pulley:


![Image](https://user-images.githubusercontent.com/114915464/214323194-638e072e-88d0-4582-91cf-eca116c5e98c.jpg)

But we need to know the situation of all the windings and any information that may be useful.



Another thing, when you start the robot, does the logger give errors?


cc @Fabrizio69 @GiacomoVassallo13

**Comment by rozliv** [comment] 2023-01-24 15:28
We loosed cables 1,2,7,8, then rotated the pulleys to be in the same position as on the other arm, and then tensioned the cables. Now it works. @AntonioConsilvio

**Comment by matejhof** [comment] 2023-01-27 06:11
Hello,
yesterday evening, the right shoulder tendons unfortunately broke again.  Now we know better how to fix it, but we're missing the tendons - especially number 1 that was missing in the original package (we used no. 3 instead, which has a different length). I gather that it was agreed during the call that you will send the no. 1 to us - is it already on the way? Please send two pieces if possible so we have spare. Thanks!   @AntonioConsilvio @Fabrizio69

**Comment by Fabrizio69** [comment] 2023-01-27 06:53
Hi @matejhof,
We are working on it, Andrea will send you the spare parts (two pieces for tendon n.1 and two pieces for tendon n.3

cc: @AntonioConsilvio

**Comment by matejhof** [comment] 2023-02-06 12:00
Thanks! Cables have arrived and the robot is fixed again. Closing!

**Closed by matejhof** 2023-02-06 12:00 UTC
Labels: iCubPrague01
