### ISSUE TITLE
Issues with yarprobotinterface, wholeBodyDynamics, and gravityCompensator

### ISSUE THREAD

**Issue by paliasgh** [robotology/icub-tech-support#1574] opened 2023-06-06 21:00 UTC
### Device name 🤖

iCubWaterloo01

### Request/Failure description

We are facing a number of issues regarding motors, especially the arms, of our iCub robot after a recent update. 
1) Changing the control mode of any joint in robot's arm to torque control mode will make the joint unavailable due to hardware fault. 
2) If we stop `yarprobotinterface` and then, start it again, the arms will not get calibrated and stay in the idle mode. 
3) `yarprobotinterface` produces lots of errors regarding cables under one board are not attached while nothing has been physically changed. 

### Detailed context

We have recently updated `iCubWaterloo01` systems to Distro `v2023.02.2` (and icub-firmware-build to `v1.34.1` consequently) as per this long [discussion](https://github.com/orgs/robotology/discussions/621). Regarding the issues listed above (log files are attached next):

1) 

Changing the control mode of any joint in robot's arm to torque control mode, either through `setControlMode(i,VOCAB_CM_TORQUE)` or directly in `yarpmotorgui`, will make the joint unavailable due to hardware fault (code 7):

![image](https://github.com/robotology/icub-tech-support/assets/59978262/46fb545f-271f-4d94-9d11-18a4d7ce97ea)

As a result, `gravityCompensator` does not seem to provide any torque to hold the arms against gravity:

https://github.com/robotology/icub-tech-support/assets/59978262/5d77a2db-824e-46b9-a14c-685ba54b05e4

We have run some tests on ports related to `yarprobotinterface`, `wholeBodyDynamics`, and `gravityCompensator`:

  ```
  icub@icub26:~$ yarp read ... /wholeBodyDynamics/left_arm/FT:i
  [INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://10.0.0.26:10003/
  [INFO] |yarp.os.impl.PortCoreInputUnit|/tmp/port/1| Receiving input from /wholeBodyDynamics/left_arm/FT:i to /tmp/port/1 using tcp

  icub@icub26:~$ yarp read ... /wholeBodyDynamics/left_arm/Torques:o
  [INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://10.0.0.26:10003/
  [INFO] |yarp.os.impl.PortCoreInputUnit|/tmp/port/1| Receiving input from /wholeBodyDynamics/left_arm/Torques:o to /tmp/port/1 using tcp
  1 1.56717448240744028354 -0.943850984098839274061 0.151011971455497440164 -0.680200214314772400037 0.0569468937549454587432 -0.0241318946280751102373 0.393043435128048235239
  1 1.56125732848709164458 -0.942025830216480564161 0.151010507049799097556 -0.711019595750900679221 0.0568831249057451041051 -0.0238640538652060384128 0.346560790373746152593
  ```
  
  ```
  icub@icub26:~$ yarp read ... /icub/left_arm/analog:o
  [INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://10.0.0.26:10003/
  [INFO] |yarp.os.impl.PortCoreInputUnit|/tmp/port/1| Receiving input from /icub/left_arm/analog:o to /tmp/port/1 using tcp
  49.346923828125 -75.0732421875 -34.97314453125 -2.5634765625 -3.753662109375 0.3662109375
  49.713134765625 -73.79150390625 -33.69140625 -2.471923828125 -3.753662109375 0.3662109375
  50.1708984375 -74.981689453125 -34.881591796875 -2.5634765625 -3.753662109375 0.3662109375
  ```
  
  ```
  icub@icub26:~$ yarp name list | grep -i analog
  registration name /iCub/left_hand/analog:o ip 10.0.0.26 port 10376 type tcp
  registration name /iCub/left_hand/analog:o/rpc:i ip 10.0.0.26 port 10375 type tcp
  registration name /iCub/right_hand/analog:o ip 10.0.0.26 port 10378 type tcp
  registration name /iCub/right_hand/analog:o/rpc:i ip 10.0.0.26 port 10377 type tcp
  registration name /icub/left_arm/analog:o ip 10.0.0.2 port 10099 type tcp
  registration name /icub/left_arm/analog:o/rpc:i ip 10.0.0.2 port 10066 type tcp
  registration name /icub/left_foot/analog:o ip 10.0.0.2 port 10104 type tcp
  registration name /icub/left_foot/analog:o/rpc:i ip 10.0.0.2 port 10071 type tcp
  registration name /icub/left_hand/analog:o ip 10.0.0.2 port 10084 type tcp
  registration name /icub/left_hand/analog:o/rpc:i ip 10.0.0.2 port 10051 type tcp
  registration name /icub/left_leg/analog:o ip 10.0.0.2 port 10102 type tcp
  registration name /icub/left_leg/analog:o/rpc:i ip 10.0.0.2 port 10069 type tcp
  registration name /icub/right_arm/analog:o ip 10.0.0.2 port 10100 type tcp
  registration name /icub/right_arm/analog:o/rpc:i ip 10.0.0.2 port 10067 type tcp
  registration name /icub/right_foot/analog:o ip 10.0.0.2 port 10103 type tcp
  registration name /icub/right_foot/analog:o/rpc:i ip 10.0.0.2 port 10070 type tcp
  registration name /icub/right_hand/analog:o ip 10.0.0.2 port 10085 type tcp
  registration name /icub/right_hand/analog:o/rpc:i ip 10.0.0.2 port 10052 type tcp
  registration name /icub/right_leg/analog:o ip 10.0.0.2 port 10101 type tcp
  registration name /icub/right_leg/analog:o/rpc:i ip 10.0.0.2 port 10068 type tcp
  ```
  
  ```
  icub@icub26:~$ yarp ping /wholeBodyDynamics/left_arm/FT:i
  This is "/wholeBodyDynamics/left_arm/FT:i" at "tcp://10.0.0.26:10161/"
  There are no outgoing connections
  There is an input connection from "/icub/left_arm/analog:o" to "/wholeBodyDynamics/left_arm/FT:i" using tcp
  There is an input connection from "<ping>" to "/wholeBodyDynamics/left_arm/FT:i" using text_ack
  ```
  
  ```
  icub@icub26:~$ yarp ping /wholeBodyDynamics/right_arm/FT:i
  This is "/wholeBodyDynamics/right_arm/FT:i" at "tcp://10.0.0.26:10162/"
  There are no outgoing connections
  There is an input connection from "/icub/right_arm/analog:o" to "/wholeBodyDynamics/right_arm/FT:i" using tcp
  There is an input connection from "<ping>" to "/wholeBodyDynamics/right_arm/FT:i" using text_ack
  ```
2) 

If we stop `yarprobotinterface` through `yarpmanager` and then, start it again, the arms will not get calibrated:

https://github.com/robotology/icub-tech-support/assets/59978262/7bfe1596-c17c-48bd-9e3a-f8a426f7a4b9

In fact, the main joints stay in idle mode (I can switch them back to position control though) and some others give fault as you can see in the screenshot below.

![image](https://github.com/robotology/icub-tech-support/assets/59978262/7d5a6b5e-a249-4c68-96fa-8c7ff7e62b99)

This means, every time we want to restart `yarprobotinterface`, we have to manually shutdown the motors (press robot's backpack's button) and start them again. It was not like this before.

3)

Based on the `yarprobotinterface` output that contains following messages,

```
[ERROR] from BOARD 10.0.1.11 (right_leg-eb11-skin), src CAN1, adr 0, time 582s 881m 129u: (code 0x00000019, par16 0x4001 par64 0x0000000000000000) ->
SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .

[ERROR] from BOARD 10.0.1.11 (right_leg-eb11-skin), src CAN2, adr 0, time 582s 884m 128u: (code 0x00000019, par16 0x3f01 par64 0x0000000000000000) ->
SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
```

we know that ["the cables on CAN1 and CAN2 under board 10.0.1.11 are not attached."](https://github.com/orgs/robotology/discussions/621#discussioncomment-5924374). In fact, no board is discovered under 10.0.1.11, as well as 10.0.1.20 and 10.0.1.21 via `FirmwareUpdater`. Could you please help us check the cables? It is strange since nothing happened to our robot physically recently that could have caused cable detachment. 

Thanks so much for your help! 

### Additional context

Here are console outputs of `yarprobotinterface`, `wholeBodyDynamics`, and `gravityCompensator` after a fresh start of the robot:

[yarprobotinterface.log](https://github.com/robotology/icub-tech-support/files/11669149/yarprobotinterface.log) (The log may contain errors related to this this [issue](https://github.com/robotology/icub-tech-support/issues/1231) that still exists (we are going to get back to this one next!).)

[gravityCompensator.log](https://github.com/robotology/icub-tech-support/files/11669152/gravityCompensator.log)
[wholeBodyDynamics.log](https://github.com/robotology/icub-tech-support/files/11669153/wholeBodyDynamics.log)

After closing `yarprobotinterface`, rerunning it produces this output (when arms are not calibrated): 

[yarprobotinterface_second_run.log](https://github.com/robotology/icub-tech-support/files/11669161/yarprobotinterface_second_run.log)

**Comment by pattacini** [comment] 2023-06-07 06:26
Thank you @paliasgh for the thorough description of the problems.

Just for our internal debug, I'll start reporting below some considerations.

#### 🔲 `WBD` (aka `wholeBodyDynamics`)

The following error caught my attention:
```console
[ERROR] |yarp.os.Network| Failure: could not find source port /icub/inertial
```

This an old name related to a deprecated way of dealing with inertial data.
At any rate, inspecting the code, I managed to track it down at this [line](https://github.com/robotology/icub-main/blob/master/src/modules/wholeBodyDynamics/observerThread.cpp#L415):

```cpp
Network::connect(string("/"+robot_name+"/inertial").c_str(), string("/"+local_name+"/unfiltered/inertial:i").c_str(),"tcp",false);
```

There's no port named `/wholeBodyDynamics/unfiltered/inertial:i`; thus, this should be just a leftover we could clean up 🧹

However, the real problem is the timeout that occurs on the MAS device, still related to the IMU, I suppose:
```console
[ERROR] |yarp.device.multipleanalogsensorsclient| No data received in the last 0.104186 seconds, timeout enabled.
```

Once in timeout, `WBD` stops its activity causing the robot to go HF 🔴 when asked to switch to torque mode.

**Comment by Nicogene** [comment] 2023-06-07 08:43
> Thank you @paliasgh for the thorough description of the problems.
> 
> Just for our internal debug, I'll start reporting below some considerations.
> #### 🔲 `WBD` (aka `wholeBodyDynamics`)
> 
> The following error caught my attention:
> 
> ```
> [ERROR] |yarp.os.Network| Failure: could not find source port /icub/inertial
> ```
> 
> This an old name related to a deprecated way of dealing with inertial data. At any rate, inspecting the code, I managed to track it down at this [line](https://github.com/robotology/icub-main/blob/master/src/modules/wholeBodyDynamics/observerThread.cpp?rgh-link-date=2023-06-07T06%3A26%3A51Z#L415):
> 
> ```c++
> Network::connect(string("/"+robot_name+"/inertial").c_str(), string("/"+local_name+"/unfiltered/inertial:i").c_str(),"tcp",false);
> ```
> 
> There's no port named `/wholeBodyDynamics/unfiltered/inertial:i`; thus, this should be just a leftover we could clean up 🧹
> 
> @Nicogene, did I get this right?


It seems that `unfilterde/inertial:i` is an old leftover but harmless, in any case @pattacini removed it https://github.com/robotology/icub-main/commit/18b7803391a871e5ad173e8a5546d17d73814ec8. We not need it since we are using the MASclient for reading the IMU

> 👉🏻 However, the real problem is the timeout that occurs on the MAS device, still related to the IMU, I suppose:
> 
> ```
> [ERROR] |yarp.device.multipleanalogsensorsclient| No data received in the last 0.104186 seconds, timeout enabled.
> ```
> 
> Once in timeout, `WBD` stops its activity causing the robot to go HF 🔴 when asked to switch to torque mode. Presumably, TBC.

Yes this should be the problem, 100 ms of delay is a lot and this

```
[ERROR] |yarp.device.multipleanalogsensorsclient| Sensor of type ThreeAxisLinearAccelerometers with index 0 has non-MAS_OK status.
```

and this:

```
[WARNING] network delays detected (1/10)
```

Are syntoms that something is not working on imu side.

Some checks that could be done are:

- Check if the imu is streaming data consistently reading from `/icub/head/inertials/measures:o`
- Try to run wbd from icub-head and see if it is still problematic.
- Check the version of the rfe w/ `FirmwareUpdater`

If on the `icub-head` wbd runs fine, it means that there are network issues between icub-head and the laptop.
If you cannot discover the rfe via `FirmwareUpdater` it means that there are issues in the CAN connection.

I recall that in the past we had issues of freeze of the board, but on the most recent firmware of rfe this problem should be fixed

cc @marcoaccame

**Comment by paliasgh** [comment] 2023-06-07 21:14
Hi @pattacini and @Nicogene , thank you very much for looking into the problem.

The port you noted streams data:

```
icub@icub26:~$ yarp read ... /icub/head/inertials/measures:o
[INFO] |yarp.os.Port|/tmp/port/1| Port /tmp/port/1 active at tcp://10.0.0.26:10003/
[INFO] |yarp.os.impl.PortCoreInputUnit|/tmp/port/1| Receiving input from /icub/head/inertials/measures:o to /tmp/port/1 using tcp
(((0.0625 0.0 0.0) 1686171416.2559928894)) (((-0.200000000000000011102 -0.359999999999999986677 -9.80000000000000071054) 1686171416.25599217415)) (((1.45624999999999999101e-05 1.71875000000000010354e-05 4.87499999999999991175e-05) 1686171416.25599265099)) () () () () () () ()
(((0.0 0.0625 0.0625) 1686171416.2660138607)) (((-0.22000000000000000111 -0.349999999999999977796 -9.81000000000000049738) 1686171416.26601314545)) (((1.45624999999999999101e-05 1.71875000000000010354e-05 4.87499999999999991175e-05) 1686171416.26601338387)) () () () () () () ()
(((0.0 0.0 0.0) 1686171416.27603173256)) (((-0.22000000000000000111 -0.340000000000000024425 -9.81000000000000049738) 1686171416.27603125572)) (((1.45624999999999999101e-05 1.71875000000000010354e-05 4.87499999999999991175e-05) 1686171416.27603149414)) () () () () () () ()
(((0.0 -0.1875 0.0) 1686171416.28613686562)) (((-0.22000000000000000111 -0.349999999999999977796 -9.81000000000000049738) 1686171416.28613615036)) (((1.45624999999999999101e-05 1.71875000000000010354e-05 4.87499999999999991175e-05) 1686171416.2861366272)) () () () () () () ()
```

It seems like `wbd` runs fine in `icub-head` (log is attached, those sensor errors are gone). I am able to enable torque control this time when `wbd` is running. Just to mention, in `wbd` logs, anything after line 321, including the sensor errors, is after when closing command is issued (through `yarpmanager` in the first log and by Ctrl+C in this log).

[wholeBodyDynamics_icub-head.log](https://github.com/robotology/icub-tech-support/files/11681836/wholeBodyDynamics_icub-head.log)

![Screenshot_2023-06-07_16-48-50](https://github.com/robotology/icub-tech-support/assets/59978262/cc00d086-f4d4-4571-b789-3fc64dcf6e3f)

Running  `gravityCompensator` in `icub-head ` still gives `[WARNING] network delays detected (1/10)` as the last output before closing the module in line 83.

[gravityCompensator_icub-head.log](https://github.com/robotology/icub-tech-support/files/11681870/gravityCompensator_icub-head.log)

We do not seem to yet have any gravity compensation in action.

Lastly, I think there are some unusual things going on regarding rfe boards. In the initial issue, I had mentioned no board is discovered under `10.0.1.11` (tactile sensors of one of the legs I think), as well as `10.0.1.20` and `10.0.1.21` (which I did not know what those could be) via `FirmwareUpdater`. Just now, I could discover one of the rfe boards, with version `1.3.0`, under `10.0.1.21`. Still nothing can be discovered under `10.0.1.20` (possibly another rfe?).

![Screenshot_2023-06-07_17-09-20](https://github.com/robotology/icub-tech-support/assets/59978262/80b1bfb6-df1c-451c-b1d2-5051f92fcefc)

**Comment by pattacini** [comment] 2023-06-08 07:07
>Running gravityCompensator in icub-head  still gives [WARNING] network delays detected (1/10) as the last output before closing the module in line 83.

It shouldn't happen but it's not operationally critical yet as the `gravityCompensator` stops working when it reaches 10 events of this type. See https://github.com/robotology/icub-main/blob/master/src/modules/gravityCompensator/gravityThread.cpp#L662-L666.

Looking at the `gravityCompensator` log, it seems all good, aside from that warning.

>We do not seem to yet have any gravity compensation in action.

What exactly have you been seeing? Are the arms falling down when switched in torque mode, although `WBD` is ok?

**Comment by pattacini** [comment] 2023-06-09 08:05
> Yes, they fall down. Having arm joints in the torque control mode with `wbd` and `gc` running is not any different (in terms of ease of moving the arm, arm falling down, etc.) from having them in the idle mode without `wbd` and `gc` running. It behaves now like this now in torque control mode:

Hi @paliasgh,
We have planned to test the `gc`'s functionality (point 1) in our next sprint (next 2 weeks). Stay tuned.

We will also organize our activities to cover points 2 and 3.

**Comment by AntonioConsilvio** [comment] 2023-06-09 10:57
Hi @paliasgh, regarding point 3:
Board 10.0.1.11 (EB11) is located in the right leg of the robot.  It should be on the outer side of the leg (obviously under the covers), as you can see from the following photos:

![image](https://github.com/robotology/icub-tech-support/assets/114915464/87945b90-f363-44b9-97d4-d853431fc650)
![Scheda eb11](https://github.com/robotology/icub-tech-support/assets/114915464/fb4be435-6738-46c1-bc67-2b9f55623107)


The EB11 board has 2 CAN connectors (CAN1 and CAN2) to which the MTB4 boards (which are screwed on the cover) must be connected. 

So, when you reach the board, you need to find the cables called 11N1 and 11N2.

The cable 11N1 connects the EB11 board to an MTB4 on the **thigh** cover.

The cable 11N2 connects the EB11 board to an MTB4 on the **ankle** cover.

Please remember to give feedback and if you have any questions, write to us. 

@paliasgh However, I don't quite understand whether you have the same error on the CAN of boards 10.0.1.20 and 10.0.1.21 or not?

cc @sgiraz @pattacini

**Comment by paliasgh** [comment] 2023-06-09 22:54
Hi @AntonioConsilvio , thanks for the help!

I opened the thigh cover and looked at the EB11 board. 11N1 was connected to one of the MTB4s in the front cover and then, to the back cover of the thigh. 11N2 was also connected to EB11, but I did not check the other end of its connection as it was going into the ankle. We do not move the robot's leg, so I think it is not very likely that a cable is disconnected. Can you please help us instead disable the leg tactile sensor, for now, to get rid of the error?

![IMG_3312](https://github.com/robotology/icub-tech-support/assets/59978262/6ffe4f60-54e5-4f80-a201-563c73249b99)

![IMG_3311](https://github.com/robotology/icub-tech-support/assets/59978262/a48af329-f420-4683-b36d-dcdd45e289ff)

![IMG_3313](https://github.com/robotology/icub-tech-support/assets/59978262/4c5ba1ac-7acc-4487-86fd-06567ff6d873)

> @paliasgh However, I don't quite understand whether you have the same error on the CAN of boards 10.0.1.20 and 10.0.1.21 or not?

I also do not know. The unusual thing that grabbed my attention was that nothing is discovered under 10.0.1.20 (see screenshot below). Should normally be something there? 

![image](https://github.com/robotology/icub-tech-support/assets/59978262/5d659760-0567-4549-b93c-bf016dbdbcea)

**Comment by AntonioConsilvio** [comment] 2023-06-12 07:26
Hi @paliasgh,

- **If you want to solve the problem**, you should test the continuity of the cables (11N1 and 11N2, just the part connecting the EB11 to the first MTB4) with a tester.

  If the continuity of the cables is good, perhaps the problem is inside the EB11 board.

  There is another test you can do: you can switch on the robot and check whether the MTB4s inside the leg have their LEDs 
  switched on or not. If they are not lit, it means that the problem is the black or red cable.

- **If you prefer to disable the tactile leg sensor**, you can go into the [robots-configuration](https://github.com/robotology/robots-configuration/tree/master/iCubWaterloo01) files and comment on these two lines inside icub_all.xml: [first](https://github.com/AntonioConsilvio/robots-configuration/blob/d2d8f4a80d4b0783d752c3826348b0d235041ca0/iCubWaterloo01/icub_all.xml#L88) and [second](https://github.com/AntonioConsilvio/robots-configuration/blob/d2d8f4a80d4b0783d752c3826348b0d235041ca0/iCubWaterloo01/icub_all.xml#L90).

  I suggest adding another comment explaining why you commented on these lines.

  This should be sufficient to disable the tactile sensors on the right leg.

Please remember to give feedback and if you have any questions, write to us.


Regarding board 10.0.1.20, it has no CAN board under it, so **it is normal** that FirmwareUpdater shows nothing.

However, if there are CAN board detached, the logger will show errors very similar to the error of the board EB11:


> ```
> [ERROR] from BOARD 10.0.1.11 (right_leg-eb11-skin), src CAN1, adr 0, time 582s 881m 129u: (code 0x00000019, par16 0x4001 par64 0x0000000000000000) ->
> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
> 
> [ERROR] from BOARD 10.0.1.11 (right_leg-eb11-skin), src CAN2, adr 0, time 582s 884m 128u: (code 0x00000019, par16 0x3f01 par64 0x0000000000000000) ->
> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
> ```

So, the board 10.0.1.20 should have no problems.

cc @sgiraz

**Comment by martinaxgloria** [comment] 2023-06-21 08:24
Hi @paliasgh,

in the past days, we did some internal tests in order to replicate your first issue (i.e. `Changing the control mode of any joint in robot's arm to torque control mode will make the joint unavailable due to hardware fault.`). In particular, we managed to run `WBD` and `gc` on `icub-head` without errors and from the yarpmotorgui we were able to switch the joints into torque control. 
We tried to put the arm in different configurations when in this control mode and we logged some values in order to understand if something happened when gc was enabled. We retrieved that actually something happens because the values are not zeros, but we have to further investigate the amount of compensation it is sending to the joints. Stay tuned!

**Comment by martinaxgloria** [comment] 2023-06-21 09:56
Moreover, doing the tests cited above, I observed the problem n.2 (i.e. `If we stop yarprobotinterface and then, start it again, the arms will not get calibrated and stay in the idle mode.`). Also in this case, we are going to investigate the problem more in depth in the next days 

cc @valegagge

**Comment by valegagge** [comment] 2023-07-05 09:03
Today I performed some tests related to the un-calibration of the arms when `yarprobotinterface` starts without switch off/on the motors.

I did the following steps:
 - switch on the motor
 - start yarprobotinterface (without calibration to speedup the tests.)
 - calibrate the fingers joint from 11 to 15 by yarprmotorgui
 - move all calibrated joints by yarprmotorgui.
 ==> until now all is ok
![Screenshot from 2023-07-05 10-23-19](https://github.com/robotology/icub-tech-support/assets/4233231/5bf545de-569c-4b54-be17-0bb5351cccef)

- stop yarprobotinterface
- start again yarprobotinterface without the calibration 
- ==> now the fingers joints are in hw fault
![Screenshot from 2023-07-05 10-52-42](https://github.com/robotology/icub-tech-support/assets/4233231/f4237965-37cc-4e23-bd30-7c6b38c2631d)

Due to the fingers fault, the calibration of the whole arm cannot be achieved.

Checking the figures above, it seems that when the controller checks the motor positions of the fingers considers them out of the range defined in the configuration, even if this is not true and moreover the motor position are almost the same in the first situation where all is fine.

This are the motor limits used. 
![Screenshot from 2023-07-05 10-58-36](https://github.com/robotology/icub-tech-support/assets/4233231/6213cf98-0b4f-4a00-8830-ee17cea8e6eb)

This is a firmware bug. We are going to fix it.

cc @MSECode

**Comment by MSECode** [comment] 2023-07-26 07:52
In relation to the [comment above](https://github.com/robotology/icub-tech-support/issues/1574#issuecomment-1621335992) here the PRs that solve the issue of the joints going in hw fault after `yarprobotinterface` restarting.

- https://github.com/robotology/icub-firmware-build/pull/95
- https://github.com/robotology/icub-firmware/pull/400

cc: @valegagge

**Comment by paliasgh** [comment] 2023-07-28 21:03
Hello @MSECode and @valegagge,

Thanks so much for working on the issue. Today, I updated the firmware of the boards to[ pull #95](https://github.com/robotology/icub-firmware-build/pull/95). For our robot, this meant updating `ems4` boards from 3.65 to 3.70, `mc4plus` boards from 3.68 to 3.73, and `strain2` boards from 2.1.0 to 2.2.0 (this last one was not part of the fix, but I assumed it is also needed for us to have the same configuration as what you tested on). There were no `mc2plus`, `amc_wr`, or `amc_wl` boards identified to update, as the title suggested. After the update, we now have:

![79D2EE64-00DD-4AAC-93DD-745774966AE7_1_102_o](https://github.com/robotology/icub-tech-support/assets/59978262/fc62d28c-c419-4890-9abb-595c9551a4ae)

![DE784E32-CB7B-4490-813D-1D67AD384DDC_1_102_o](https://github.com/robotology/icub-tech-support/assets/59978262/f68b304e-c52b-42c7-8a0d-f9d15ad628e4)

![32F7D132-EB3D-486B-A79F-675C0124A11A_1_102_o](https://github.com/robotology/icub-tech-support/assets/59978262/eb847473-fa3f-4115-bcf0-e929180a3b5f)

During the update, something happened that caused another, even more serious, issue! One `strain2` board, under 10.0.1.6, got disappeared during the update (similar to [this issue](https://github.com/orgs/robotology/discussions/621#discussioncomment-5921185) with another board). You can compare the photo below, taken before updating `strain2`'s, with the second photo above. I tried restarting everything, but still `FirmwareUpdater` no longer sees it.

![35FD7D02-5825-499A-BBBD-23150657DB3C_1_201_a](https://github.com/robotology/icub-tech-support/assets/59978262/02e0738b-6586-4400-b289-bf1140d71cba)

Now, `yarprobotinterface` can not even run due to errors regarding that board, mainly:

```
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 86s 654m 427u: (code 0x00000013, par16 0x0001 par64 0x0000000000000000) -> SYS: the EOtheInfoDispatcher could not accept a eOmn_info_properties_t item inside its transmitting queue. In par16 there is the number of lost items. + . 
[ERROR]  from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src CAN2, adr 0, time 86s 621m 128u: (code 0x00000019, par16 0x4001 par64 0x0000000000000000) -> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + . 
```
Here is a complete log:

[yarprunlog_28_07_2023_14_28_17.log](https://github.com/robotology/icub-tech-support/files/12198163/yarprunlog_28_07_2023_14_28_17.log)

Thanks again for your support.

**Comment by MSECode** [comment] 2023-07-28 21:07
cc: @marcoaccame @sgiraz @mfussi66 
If I'm not mistaken the problem reported above and reported here:

"During the update, something happened that caused another, even more serious, issue! One strain2 board, under 10.0.1.6, got disappeared during the update"

seems similar to one we had updating the strain2.

**Comment by paliasgh** [comment] 2023-09-29 20:19
Hello @pattacini, @MSECode, @valegagge, and everyone,

I wanted to follow up on the status of this issue. As I reported [here](https://github.com/robotology/icub-tech-support/issues/1574#issuecomment-1656332321), the [fix](https://github.com/robotology/icub-tech-support/issues/1574#issuecomment-1651167024) did not solve the issue of the joints going in hw fault after `yarprobotinterface` restarting in our robot. Is there anything we need to check again? Thanks a lot.

**Comment by MSECode** [comment] 2023-10-02 07:57
That's unexpected, since I've just updated a robot, which should have the same sw and hw architecture of yours, with the latest Distro and firmware a couple of days ago and we had no issues. 
Anyways, @valegagge @pattacini,  should we organize a call all together to dig into the issue and solve that asap. Does it make sense to you?

**Comment by valegagge** [comment] 2023-10-02 08:55
> Anyways, @valegagge @pattacini, should we organize a call all together to dig into the issue and solve that asap. Does it make sense to you?

Hi @paliasgh,
as the first thing, I suggest updating the entire robot to the [new distro 2023.08.0](https://github.com/orgs/robotology/discussions/655). 

If you still have the issue related to the strain boards, please tell us.

**Comment by paliasgh** [comment] 2023-10-02 17:42
Hello @valegagge,

I updated our systems and the robot to `v2023.08.0`. We still have an issue with `strain2` boards. When updating the firmware to `v1.36.0` today, `strain2` boards under 10.0.0.3 and 10.0.1.7 also got disappeared. It seems like 10.0.0.3 is for the robot's right arm, so we no longer even have the upperbody of the robot working. Basically, there are only two `strain2` boards left that can be seen. The rest are all gone!

![Screenshot_2023-10-02_13-38-07](https://github.com/robotology/icub-tech-support/assets/59978262/bf514823-d75b-4a01-aedf-c51f44cdce35)

**Comment by valegagge** [comment] 2023-10-04 13:49
Hi @paliasgh,
for sure you need to update the configuration by setting the the 2.2.0 as fw version as @MSECode said before.

Anyway, we can verify that the update to the new distro works fine without the strain and then fix the strain issue.

So, you need to remove the strain boards configurations and their wrappers from the configuration file:
![image](https://github.com/robotology/icub-tech-support/assets/4233231/8ef3beee-e926-43ae-a51d-cbc3fbd6c33d)

I prepared `waterloo_icub_all_no_strain.txt` for you which starts all devices except the strain. Could you try to run  `yarprobotinterfece` and all should be ok. 
[waterloo_icub_all_no_strain.xml.txt](https://github.com/robotology/icub-tech-support/files/12804149/waterloo_icub_all_no_strain.xml.txt)

Obviously, you cannot run wholeBodyDynamics without strain.

**Comment by paliasgh** [comment] 2023-10-04 15:50
Hello @MSECode and @valegagge,

- Regarding the version conflict, I set `2.2.0` in all the `xml` files in `iCubWaterloo01/hardware/FT`. This should be everything that needed to be changed, right? That fixed the left arm. Thanks.

- I could start the robot, entirely, with `waterloo_icub_all_no_strain.xml` configuration. The new distro works fine. In fact, one of the original problems (If we stop `yarprobotinterface` and then, start it again, the arms will not get calibrated and stay in the idle mode.) is solved with the update! Thanks a lot. 

Here is a log file when running `yarprobotinterface`.
[yarprunlog_04_10_2023_11_48_34.log](https://github.com/robotology/icub-tech-support/files/12805426/yarprunlog_04_10_2023_11_48_34.log)

**Comment by MSECode** [comment] 2023-10-04 15:55
Hi @paliasgh,

- first point is correct. That should be all. All the data related to the CAN configuration of the strain should  be thre.
- good news for the second point. That's great.
- We are investigating on the problem related to the impossibility to discover the `strain` in some conditions

Thanks for the udpate

**Comment by Nicogene** [comment] 2023-10-06 09:07
Hi @paliasgh,

in the meanwhile you could use `wholeBodyDynamics` without ft sensors running with the option `--dummy_ft`, see https://github.com/robotology/icub-main/blob/bd74c24d0aae5918d62a97ad3354ed5793a0b0f7/src/modules/wholeBodyDynamics/main.cpp#L529C34-L529C34

**Comment by paliasgh** [comment] 2023-10-19 22:30
Hello @MSECode,

Many thanks! It seems to be working. Two things to check, just to make sure:

- I could not discover any `strain2` boards under 10.0.1.5. Is this normal?

<img width="856" alt="Screenshot 2023-10-19 at 6 26 47 PM" src="https://github.com/robotology/icub-tech-support/assets/59978262/b164752c-6306-4e5b-8777-bd257a48def8">

Doing the procedure for boards 10.0.1.10 and 10.0.1.11 led to the discovery of 13 `mtb4` boards under each address, which are not seen normally. Should I update all these as well? It seems like I need to do it one by one, since they get lost in case I update them all at once.

![image](https://github.com/robotology/icub-tech-support/assets/59978262/3d3d6d14-5e82-4bbd-b888-68654755a1da)

**Comment by MSECode** [comment] 2023-10-20 10:08
Hi @paliasgh,
 - regarding the first point it is normal you do not have `strain2` boards under the `ETH` board `10.0.1.5`, since it is the torso board, and as you can see from the image below, there not any FT sensor configured for them. So that's fine, no `strain2` for 10.0.1.5

![image](https://github.com/robotology/icub-tech-support/assets/77933235/3380bb9f-6f71-4e0e-9b92-f154cca54c87)

- regarding the `mtb4` CAN boards, it is not needed to update them. They firmware did not change.

cc: @pattacini @valegagge @sgiraz @Nicogene

**Comment by sgiraz** [comment] 2023-11-29 15:12
Hi @paliasgh,

Do you have any news on this issue?
If everything is okay, I will proceed to close it..

**Comment by paliasgh** [comment] 2023-11-30 21:07
Hello @sgiraz,

Thanks for checking with us. I was busy with another project during the past months so I was not fast responding here. I did some tests today and everything with `yarprobotinterface` looks fine! in fact, all the 3 original problems are resolved. 

Thanks again @MSECode @pattacini @valegagge @sgiraz @Nicogene @martinaxgloria @AntonioConsilvio for all the support!

**Closed** 2023-12-04 13:39 UTC
Labels: iCubWaterloo01 S/N:044
