### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left index add does not move

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-tech-support#1776] opened 2024-03-11 17:23 UTC
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

`l_index_add` does not move when a setpoint is commanded, while we are able to manually move the finger and read the right position when it is in idle.

### Detailed context

![Screenshot from 2024-03-11 18-22-18](https://github.com/robotology/icub-tech-support/assets/143645988/08588058-1015-4f0a-a6a6-8a5d8434b2d1)
![Screenshot from 2024-03-11 18-22-12](https://github.com/robotology/icub-tech-support/assets/143645988/a684e1fe-8af2-4467-a2a1-28f77d70977d)
![Screenshot from 2024-03-11 18-22-06](https://github.com/robotology/icub-tech-support/assets/143645988/f98ffeba-16b9-4251-aa4c-2bb56a3f8ca3)

**Comment by AntonioConsilvio** [comment] 2024-05-22 09:00
Hi @PasMarra! The cause and solution of this issue is described in this comment:

- https://github.com/robotology/icub-tech-support/issues/1775#issuecomment-2124235924

Here the video of the left arm:

https://github.com/robotology/icub-tech-support/assets/114915464/de94397a-581b-44a5-83ed-9df07b76c168

Closing!

**Closed by AntonioConsilvio** 2024-05-22 09:00 UTC
Labels: ergoCub 1.1 S/N:001
