### ISSUE TITLE
iCubGenova09 (iRonCub3) S/N:000 – Left elbow doesn't calibrate

### ISSUE THREAD

**Issue by davidegorbani** [robotology/icub-tech-support#1815] opened 2024-05-23 17:04 UTC
### Robot Name 🤖

iCubGenova09 (iRonCub3) S/N:000

### Request/Failure description

The right elbow doesn't calibrate, when we try to calibrate it with the yarpmotorgui, it trows the following error in the yarplogger:

![Screenshot from 2024-05-23 19-00-13](https://github.com/robotology/icub-tech-support/assets/101326942/a60c8074-a3df-4bfb-ab79-acf6ec6127cb)

### Detailed context

We were trying to start the robot and all the joints calibrated but the the left elbow, then we proceeded calibrating it with the yarpmotorgui but it failed.

**Comment by gabrielenava** [comment] 2024-05-23 17:05
cc @DanielePucci

**Comment by gabrielenava** [comment] 2024-05-27 09:20
while unmounting the cover with @AntonioConsilvio and @AntonioAzocar we noted that the power supply cabl was damaged:

![image](https://github.com/robotology/icub-tech-support/assets/12396934/ec548d7a-bfdf-4aae-bb14-e07cc10d5dc6)

might be related

**Comment by AntonioAzocar** [comment] 2024-05-27 11:48
> while unmounting the cover with @AntonioConsilvio and @AntonioAzocar we noted that the power supply cabl was damaged:
> 


Fixed!

![cavo_alim](https://github.com/robotology/icub-tech-support/assets/130973726/8b52d47e-911d-4323-8760-f21df458a23a)


Now we can mount it on the robot and test it.

cc @AntonioConsilvio

**Comment by AntonioConsilvio** [comment] 2024-05-28 06:58
Hi @davidegorbani @gabrielenava, @AntonioAzocar intervention was helpful, but unfortunately not decisive.

So, I tried replacing the 2FOC board and tested the robot, which seems to be working properly.

However, I await your feedback before closing the issue!

**Comment by gabrielenava** [comment] 2024-05-28 07:08
thank you @AntonioConsilvio! We'll test the robot in the next days to confirm if the problem is fixed!

**Comment by davidegorbani** [comment] 2024-05-29 09:54
We tested the robot yesterday and today during the demo and on both occasions, it successfully started. Thank you @AntonioAzocar @AntonioConsilvio!

**Comment by AntonioConsilvio** [comment] 2024-05-29 11:00
Thank you for the feedback! Closing!

**Closed by AntonioConsilvio** 2024-05-29 11:00 UTC
Labels: iCubGenova09 (iRonCub3) S/N:000
