### ISSUE TITLE
ergoCub 1.0 S/N:000 – Jumps on the right ankle roll position mesaurements

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-tech-support#1631] opened 2023-09-06 15:36 UTC
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

Today while the robot was tethered to the crane, we heard the same noise of https://github.com/robotology/icub-tech-support/issues/1603. 

### Detailed context

We collected one dataset where the robot was supposed to be still and we noticed wired jumps on the right ankle roll position as can be seen in the following plot

![image](https://github.com/robotology/icub-tech-support/assets/16744101/4f57663b-6c6d-4abb-85ad-a9c3f8824764)

Here is the dataset that can be used to deeply investigate the issue [robot_logger_device_2023_09_06_15_17_29.zip](https://github.com/robotology/icub-tech-support/files/12539736/robot_logger_device_2023_09_06_15_17_29.zip)

### Additional context

This may eventually cause the worsening of https://github.com/robotology/icub-tech-support/issues/1614

cc @S-Dafarra @lrapetti @mebbaid @isorrentino @paolo-viceconte

**Comment by maggia80** [comment] 2023-09-07 06:59
@AntonioConsilvio we could add the same ferrites used in the left ankle

**Comment by sgiraz** [comment] 2023-09-07 09:09
see also #1603 

cc @GiulioRomualdi

**Comment by vigisushrutha23** [comment] 2023-09-10 12:04
Today we also observed those jumps running some experiments on the robot

**Comment by AntonioConsilvio** [comment] 2023-09-12 07:27
I put the ferrite on the robot's ankle, so I would ask you to retest for the presence of these spikes.

![Ferrite](https://github.com/robotology/icub-tech-support/assets/114915464/ce34266e-380f-4790-91e6-7df3fb847eb4)

cc @sgiraz @GiulioRomualdi

**Comment by sgiraz** [comment] 2023-09-19 10:22
Hi @GiulioRomualdi, @vigisushrutha23 

Do you have any feedback on this issue, after the fix applied by @AntonioConsilvio?

**Comment by vigisushrutha23** [comment] 2023-09-19 16:04
I head much lesser noise and the side-stepping seemed much smoother for my experiments done last week when compared to experiments done on or before 10-09. I shall add more feedback next week when I do more experiments.

**Comment by sgiraz** [comment] 2023-09-25 10:46
Hi @vigisushrutha23,   

Thanks for your feedback.

In the meantime, I will proceed to close this issue since it appears to have been resolved based on the feedback posted above. Please feel free to reopen it if needed.

cc @AntonioConsilvio

**Comment by sgiraz** [comment] 2023-10-09 09:26
Hi @vigisushrutha23, 
Did you have the opportunity to perform some tests as mentioned above?
If they went well, I would close this issue as the problem is solved.

**Comment by sgiraz** [comment] 2023-10-18 20:38
cc @GiulioRomualdi

**Comment by GiulioRomualdi** [comment] 2023-10-19 05:44
Hi @sgiraz in the last week, I didn't used the robot. However @paolo-viceconte @lrapetti and @evelyd used it quite a lot so they can comment on this

**Comment by vigisushrutha23** [comment] 2023-10-19 06:32
@sgiraz Sorry for the late reply. Simone and I had some some side-stepping experiments on the robot and after a few side-steps or in the second or third experiments, we observed jumps, irregular double stepping on the same foot and unstable walking. I am not entirely sure if they were only the right foot though because from surface level observation it seemed the jumps and double steps happened sometimes on the left leg as well.

**Comment by lrapetti** [comment] 2023-10-19 07:40
> However @paolo-viceconte @lrapetti and @evelyd used it quite a lot so they can comment on this

I did not observe particular behaviour.

**Comment by paolo-viceconte** [comment] 2023-10-19 08:53
> > However @paolo-viceconte @lrapetti and @evelyd used it quite a lot so they can comment on this
> 
> I did not observe particular behaviour.

Me neither. I also checked the logs of a few experiments we performed yesterday and they do not seem to contain spikes of the ankle rolls as those shown in https://github.com/robotology/icub-tech-support/issues/1631#issue-1884279938.

**Comment by sgiraz** [comment] 2023-10-19 21:36
> @sgiraz Sorry for the late reply. Simone and I had some some side-stepping experiments on the robot and after a few side-steps or in the second or third experiments, we observed jumps, irregular double stepping on the same foot and unstable walking. I am not entirely sure if they were only the right foot though because from surface level observation it seemed the jumps and double steps happened sometimes on the left leg as well.

Hi @vigisushrutha23, 

Can you remember the time you experienced the issues. It is a quite important information for us in order to track the problem in relation to our maintenance activities. For example if the problem on the left ankle happen before the #1662 it may be already solved now.

**Comment by vigisushrutha23** [comment] 2023-10-20 10:58
@sgiraz I think we did the testing before the fix of #1662. We shall be testing today and let you know. If there are no problems this can be permanently closed .

**Comment by vigisushrutha23** [comment] 2023-10-23 09:16
@sgiraz  We didn't get to test the sidestepping due to some issue with parameters and lack of time. The normal walking worked just fine. So i think this issue can be closed.

**Comment by sgiraz** [comment] 2023-10-23 11:04
Ok, so I proceed to close this issue. 

Thanks to all for your feedback! 🦾

Feel free to reopen if necessary.

cc @AntonioConsilvio @vigisushrutha23 @lrapetti @GiulioRomualdi

**Closed by sgiraz** 2023-10-23 11:04 UTC
Labels: ergoCub 1.0 S/N:000
