### ISSUE TITLE
R1SN003 left shouder, left hand, right hand and neck issues

### ISSUE THREAD

**Issue by elandini84** [robotology/icub-tech-support#1293] opened 2022-02-07 15:00 UTC
### Device name 🤖

R1SN003

### Request/Failure description

R1 left sholder seems to have loosened up and the left hand does not work properly.

### Detailed context

As can be seen in the following video the left shoulder of R1SN003 seems to have loosened up
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53729815/152760990-f69de281-352d-4216-8773-f20d421d44a8.gif)

For the other issue, the left hand of the robot does not starts properly (it starts in `idle` as can be seen from the following video). If, from `yarpmotorgui` the `Run` button is pressed for both the left hand joints, no error is thrown and the encoders seem to work, but it is not possible to move any of them.

https://user-images.githubusercontent.com/62991576/152811616-a0190865-61b2-4721-9800-a3ae0f140f3c.mp4

From 0:53 to 1:16 I tried to gently move the hand joints in order to se if the encoders would have followed and that seems so. From 1:17 onwards, as can be clearly seen, moving the slider does not affect the actual position of the joint.

### Additional context

Regarding the left hand issue, even though I wasn't able to find any useful information in the `yarprobotinterface` log, I'm going to post it here in case you wanted to take a look at it.

[R1SN003_yarprobotinterface_log.txt](https://github.com/robotology/icub-tech-support/files/8016253/R1SN003_yarprobotinterface_log.txt)

**Comment by emilianob80** [comment] 2022-02-09 05:46
The problem with the hand could be caused by this screw which was inside the hand on the MC2 electronic board. It may have caused component U4 to burn out.
It is difficult to tell if it was the EMC test that caused the damage because the right hand was not damaged

![IMG_20220209_063521](https://user-images.githubusercontent.com/53729815/153128450-c22731a5-2af6-42ad-b2ea-57bc158824cc.jpg)
![IMG_20220209_064339__01](https://user-images.githubusercontent.com/53729815/153129411-a52ed252-48a8-4cfa-8c8a-10bf84a9d71e.jpg)


I am replacing the EB9 electronic board

**Comment by fbiggi** [comment] 2022-02-09 05:55
inizio fase di smontaggio ore 06:00 

![WhatsApp Image 2022-02-09 at 06 48 34](https://user-images.githubusercontent.com/20420331/153130268-6a73c5a8-2c1f-4760-bc98-c2129b3947b7.jpeg)

La spalla sx presenta le viti TB 4X16 allentate, procedo a serrare con Frenafiletti

![WhatsApp Image 2022-02-09 at 06 48 34 (1)](https://user-images.githubusercontent.com/20420331/153130531-b2b1beec-77db-4c38-9198-790271d3ca1e.jpeg)

**Comment by emilianob80** [comment] 2022-02-09 06:49
The card has been replaced and programmed.

![eb9](https://user-images.githubusercontent.com/53729815/153136416-72a9aad7-bd67-4ce1-b2d3-8782369806ed.JPG)

**Comment by emilianob80** [comment] 2022-02-09 08:18
@elandini84 The robot has been repaired. It is necessary to test it before closing the last covers

**Comment by emilianob80** [comment] 2022-02-09 11:28
@elandini84 please can you please correct the title and add right hand and neck

**Comment by emilianob80** [comment] 2022-02-09 11:34
The MC4_PLUS electronic board in package EB10 appeared to have burnt component U4. It has been replaced and scheduled. Unloading in the warehouse carried out

![c12dacb2-aad8-448b-a84d-34786f9339f8](https://user-images.githubusercontent.com/53729815/153191846-e510ad29-ded8-459c-b6f1-b65a81fb8628.jpg)

![d1000084-cf0a-4df9-b13a-7b2197484989](https://user-images.githubusercontent.com/53729815/153191838-550fb2a8-78c6-4e38-a213-f1992b6dc222.jpg)

**Comment by emilianob80** [comment] 2022-02-09 11:36
After the functional test, the right thumb cord was found to be broken. @fbiggi  is providing for the replacement

**Comment by emilianob80** [comment] 2022-02-10 13:07
@elandini84 robot repaired and working. I proceed with the closure of the issue

**Closed by emilianob80** 2022-02-10 13:07 UTC
Labels: R1SN003
