### ISSUE TITLE
[ergoCubSN000] ergoCub power goes to protection 0VP

### ISSUE THREAD

**Issue by lrapetti** [robotology/icub-tech-support#1587] opened 2023-06-26 14:27 UTC
### Device name 🤖

ergoCubSN000

### Request/Failure description

The power supply goes in protection when we move the power cable.

### Detailed context

It happens only if the Sense is connected, disconnecting the sense it never happens.

https://github.com/robotology/icub-tech-support/assets/35487806/af96311b-0bf5-46cc-a0ae-613bdbde8464

cc @maggia80 @MrAndrea

**Comment by AntonioConsilvio** [comment] 2023-06-27 09:10
Hi, the power supply shows this error: 


![Image](https://github.com/robotology/icub-tech-support/assets/114915464/7d17a1a3-b459-4fd0-adbc-eda686d3a862)

It it happens when someone touch the Sense cable. 

cc @maggia80 @MrAndrea

**Comment by maggia80** [comment] 2023-06-27 11:28
ok, make sense. We should check if the remote sense is well connected.

**Comment by sgiraz** [comment] 2023-07-12 16:11
Hi @AntonioAzocar, 

The robot is now operative again. We can proceed to test the sense with the robot attached.

**Comment by sgiraz** [comment] 2023-07-14 13:34
Ok, we spotted that the red (positive) cable wasn't properly connected to the power supply `sense` connector.
Once reconnected correctly the problem is solved.

Thanks, @AntonioAzocar and @Gandoo for the check and fix.
Closing.

@lrapetti

**Closed by sgiraz** 2023-07-14 13:34 UTC
Labels: ergoCub S/N:000
