### ISSUE TITLE
ergoCub 1.0 S/N:000 – Cannot start the robot

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1958] opened 2024-11-11 17:00 UTC
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

Today I tried to use the robot and it was not starting because of this error

![Image](https://github.com/user-attachments/assets/f91278b4-76dc-4094-adbd-ff69754d8761)

### Detailed context

cc @Miche19 @S-Dafarra

**Comment by SimoneMic** [comment] 2024-11-11 17:10
I think that is the same issue mentioned here: https://github.com/robotology/icub-tech-support/issues/1956

**Comment by isorrentino** [comment] 2024-11-11 21:34
@SimoneMic I don't think so, the error is related to different boards.

**Comment by AntonioConsilvio** [comment] 2024-11-12 10:45
Hello @isorrentino @SimoneMic the problem originates from the AMC EB31 which has a small fault. Sometimes it does not start in `eApplication`, but in `eUpdater`.

For now there are no plans to replace the board, as a walkaround you can do the following steps.

Start `FirmwareUdater -a` on the robot torso. Select the board and click on `Set Def Boot eApplication` (1) and `Force ETH Application` (2).

![Image](https://github.com/user-attachments/assets/b5c70281-e3c8-4d0c-9c35-71039ca61043)

The robot will run correctly until the problem occurs again.

The problem is tracked internally, so I'm closing this issue and if we will work on upgrading the robot in the future, we will proceed with replacing the board.

**Closed by AntonioConsilvio** 2024-11-12 10:45 UTC
Labels: ergoCub 1.0 S/N:000
