### ISSUE TITLE
ergoCub 1.0 S/N:000 – Realsense depth detects points mid-air

### ISSUE THREAD

**Issue by SimoneMic** [robotology/icub-tech-support#1626] opened 2023-08-30 14:34 UTC
### Robot Name 🤖

ergoCub 1.0 S/N:000

### Request/Failure description

The depth pointcloud of the realsense detects some points mid-air, near the end of the field of view of the camera, where there should be none.
[depth_flicker.webm](https://github.com/robotology/icub-tech-support/assets/86918431/b21fdc47-32d6-46e5-8257-0866bfb0f804)
![DepthNoise](https://github.com/robotology/icub-tech-support/assets/86918431/332620a4-f7cb-414a-afe5-a3c6e10b5970)

I suggest to remove the outer plexiglass panel that is in front of the realsense's sensors. This should also reduce the noise of the realsense, since dirt or signs on the glass, could interfere with the ambient light.
![realsense_plexiglass_side](https://github.com/robotology/icub-tech-support/assets/86918431/7c67d5e9-edc4-4488-8b00-aabbf448aa32)

### Detailed context

See above

### How does it affect you?

The suddent appearance of points this close, in navigation, are considered as obstacles. 
These obstacles are inflated to ensure a safety distance from the robot. This means that this flickering leads to strange and contorted paths, or navigation faults/arrests.

**Comment by sgiraz** [comment] 2023-09-01 15:26
> I suggest to remove the outer plexiglass panel that is in front of the realsense's sensors. This should also reduce the noise of the realsense, since dirt or signs on the glass, could interfere with the ambient light.

Hi @SimoneMic, We'll discuss and evaluate your suggestion asap.

cc @Mick3Lozzo @Nicogene @maggia80 @Fabrizio69

**Comment by Nicogene** [comment] 2023-09-05 08:48
We are aware that the plastics on ergoCubSN000 are not perfectly transparent, so we planned to produce better plexiglass for ergoCubSN001 and replace the one in ergoCubSN000.

If also w/ the new plexiglass problem persists we will consider other solutions.

cc @maggia80 @pattacini @Fabrizio69

**Comment by maggia80** [comment] 2023-09-12 11:11
we received the parts for replacing the plexiglass with a new one.

**Comment by AntonioConsilvio** [comment] 2023-09-14 09:31
Hi @SimoneMic, I replaed the plexiglas with a new one. The latter looks clean and in good condition.

However, give us a feedback after your tests.

cc @maggia80 @sgiraz @Fabrizio69

**Comment by sgiraz** [comment] 2023-09-25 10:55
Hi guys,

Any feedback on this? 

cc @SimoneMic

**Comment by sgiraz** [comment] 2023-10-09 09:23
I guess the problem is solved. Closing.

**Closed by sgiraz** 2023-10-09 09:23 UTC
Labels: ergoCub 1.0 S/N:000
