### ISSUE TITLE
ergoCub 1.1 S/N:001 – Left hip roll goes in HF while walking 

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-tech-support#1708] opened 2023-12-15 13:18 UTC
### Robot Name 🤖

ergoCub 1.1 S/N:001

### Request/Failure description

The left hip roll joint goes into hardware fault as soon as the robot starts walking.

Here the video.

https://github.com/robotology/icub-tech-support/assets/43743081/5afd825b-8364-4bf4-a84b-090b789dac98

### Detailed context

Here is the log file

[log_ergocub-torso_yarprobotinterface_1154.txt](https://github.com/robotology/icub-tech-support/files/13685563/log_ergocub-torso_yarprobotinterface_1154.txt)

![overcurrent](https://github.com/robotology/icub-tech-support/assets/43743081/d505ed0b-6e00-4015-89b8-d56ad2c471f7)

cc @DanielePucci @GiulioRomualdi

**Comment by DanielePucci** [comment] 2023-12-16 18:50
Most likely, the motor was burned after one-foot balancing experiments since that motor was pretty hot. This is another element for the importance of the temperature protection feature that is currently being implemented by iCub Tech, and that hopefully will be deployed onto the robot soon.

CC
@ale-git @valegagge

**Comment by GiulioRomualdi** [comment] 2023-12-18 10:54
Hi all, by any chance, if the motor is burned, is there another one to replace it?

**Comment by maggia80** [comment] 2023-12-18 12:11
@GiulioRomualdi yes we have two more motors left. The problem is that we have zero mech guys till Gen 2nd...

**Comment by mebbaid** [comment] 2023-12-18 12:28
We were trying an integration experiments with HSP maniupulation team using the walking controllers, but this issue is blocking.

**Comment by fbiggi** [comment] 2024-01-03 09:16
LLM1 engine replaced
work carried out see    [issue](https://github.com/icub-tech-iit/proto/issues/2680) PROTO
I deliver the robot to for testing to @AntonioConsilvio 

@Fabrizio69 @maggia80

**Comment by maggia80** [comment] 2024-01-03 09:38
@AntonioConsilvio we should change the current limit for this motor type **MOOG_C2900576_ROTOR** (see cub-tech-iit.github.io/documentation/ergoCub1/ergoCub1-joints) to:

```
 <param name="motorNominalCurrents">             5000                     </param>
        <param name="motorPeakCurrents">        10000               </param>
        <param name="motorOverloadCurrents">    15000           </param>
        <param name="motorPwmLimit">            18000               </param>
```

**Comment by sgiraz** [comment] 2024-01-04 16:03
A PR on `robot-configuration` with the changes mentioned above will follow soon.

cc @AntonioConsilvio

**Comment by SimoneMic** [comment] 2024-01-22 09:42
Hello,

Has this issue been solved?
Can we use the robot in its current state or do we need to take some further precautions?

Thanks!

**Comment by AntonioConsilvio** [comment] 2024-01-22 09:57
Hi @SimoneMic, As long as the temperature reading on the robot is not fully functional, the current limits will not change as it would cause the hip roll i2t HW fault during walking.

So, the usable current limits are still the same (devel).

**Comment by sgiraz** [comment] 2024-03-14 17:07
Hi @GiulioRomualdi,

To definitively close this issue we'd need someone who does the robot walking. 
Can you assist @AntonioConsilvio w/ this task?

cc @DanielePucci

**Comment by AntonioConsilvio** [comment] 2024-05-29 12:03
Hi! We tested [these current limits](https://github.com/robotology/icub-tech-support/issues/1708#issuecomment-1875082561) on ergoCubSN002:
> ````
> <param name="motorNominalCurrents">             5000                     </param>
>        <param name="motorPeakCurrents">        10000               </param>
>        <param name="motorOverloadCurrents">    15000           </param>
>        <param name="motorPwmLimit">            18000               </param>
> ````

The robot works but the joint tracking is less accurate, negatively affecting the walking. 

So more studies can be done on this to verify its feasibility, however I am proceeding with the closure of this issue as the burnt-out motor has been successfully replaced!

**Closed by AntonioConsilvio** 2024-05-29 12:03 UTC
Labels: ergoCub 1.1 S/N:001
