### ISSUE TITLE
Left hand eb25-j8_11 goes to not-configured status under stress

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-tech-support#1130] opened 2021-05-04 08:40 UTC
### Robot name 🤖

icubGenova09

### Request/Failure description

Following the issue in https://github.com/robotology/icub-tech-support/issues/1048, we still face the problem with iCub left hand eb25-j8_11 board. 

### Detailed context

When the robot interacts with the environment or when there is a large error between the robot desired position direct desired and feedback value (i.e., under stress), the board goes to `not-configured` status and as a result we need to restart the `yarprobotinterface`. This happened during teleoperation scenarios with `position-direct` control mode. Later, we will provide further information that can help for debugging. Back in time we tried to reduce the PWM maximum vallue (if I am not it was [`motorPwmLimit`](https://github.com/dic-iit/robots-configuration/blame/a2ee16f9f6e8624b1fd558cc4e16f8cea05a4123/iCubGenova09/hardware/motorControl/left_arm-eb25-j8_11-mc.xml#L21-L22)), but this is not a viable solution since it significantly degrades the control performance.

CC @DanielePucci  @S-Dafarra

**Comment by S-Dafarra** [comment] 2021-05-04 08:44
This is something that does not happen on the iCubGenova04. It is crucial that the joints do not reach this unrecoverable state.

cc @pattacini @maggia80

**Comment by pattacini** [comment] 2021-05-04 09:03
Looking at the past issue as well, it'd worth replacing the board, probably.

**Comment by S-Dafarra** [comment] 2021-05-04 10:02
@kouroshD does it happens on both arms?

**Comment by marcoaccame** [comment] 2021-05-04 15:07
First suggestion is to post the whole log file. From that we can see if the board resets and hence restarts.
If I am not wrong (pls @ale-git confirm it) at startup the board puts the joints in `not-configured` state.

**Comment by kouroshD** [comment] 2021-05-21 15:12
Here is the result for the left hand, when it goes to not-configured status:

![IP](https://user-images.githubusercontent.com/17707730/119159389-74d57780-ba57-11eb-8400-413834f2ad73.png)
![TD](https://user-images.githubusercontent.com/17707730/119159391-756e0e00-ba57-11eb-9d67-24d573fab9ae.png)
![TO](https://user-images.githubusercontent.com/17707730/119159392-7606a480-ba57-11eb-881a-d8f875fac48c.png)
![TP](https://user-images.githubusercontent.com/17707730/119159396-7606a480-ba57-11eb-97f8-613c3bd16127.png)
[data-plotter.zip](https://github.com/robotology/icub-tech-support/files/6523441/data-plotter.zip)

I have added the logged data file and a MATLAB code to plot the data.

@pattacini @marcoaccame @S-Dafarra

**Comment by kouroshD** [comment] 2021-05-21 15:26
I tried with the right hand as well. 

![TD](https://user-images.githubusercontent.com/17707730/119161182-4eb0d700-ba59-11eb-8e83-6c15d3d92a8e.png)

![TO](https://user-images.githubusercontent.com/17707730/119161184-4eb0d700-ba59-11eb-8db2-272c807cada7.png)
![TP](https://user-images.githubusercontent.com/17707730/119161186-4f496d80-ba59-11eb-9637-cff6bf16f58e.png)


![IP](https://user-images.githubusercontent.com/17707730/119161180-4e184080-ba59-11eb-895a-38207791f82e.png)

**It happened after 40 seconds, when start grasping an object.**
Before that, the tracking is not good as well due to https://github.com/robotology/icub-tech-support/issues/1058#issuecomment-845898772 which is only related to right hand

It goes to not-configured status, similar to left hand.

@pattacini @marcoaccame @S-Dafarra @DanielePucci @ale-git  @maggia80

**Comment by pattacini** [comment] 2021-05-21 15:53
Thanks @kouroshD 👍🏻 
I reckon that @marcoaccame aimed to see the log of the `yarplogger` as well in order to inspect some diagnostics. Do you have it?

Also, could you please clarify the following points:
- What's the range of the finger joints of the left hand? Are they scaled somehow? They seem to be moving of just fractions of degrees. The right hand, instead, looks better in this respect.
- What are the units of the x-axis? Seconds? There seems to be a mismatch between the left and right hand in this regard.

**Comment by kouroshD** [comment] 2021-05-21 16:29
> What's the range of the finger joints of the left hand? Are they scaled somehow? They seem to be moving of just fractions of degrees. The right hand, instead, looks better in this respect.

My bad, I did not transformed them to degree. They were in radians. I have updated the figures.

> What are the units of the x-axis? Seconds? There seems to be a time mismatch between the left and right hand in this regard.

Again, it was samples in that case. I have updated the figures. They are in seconds now.

**Comment by kouroshD** [comment] 2021-05-21 16:43
@pattacini  This is yarprobotinterface logger info:

[log_icub-head_yarprobotinterface_16718.txt](https://github.com/robotology/icub-tech-support/files/6523963/log_icub-head_yarprobotinterface_16718.txt)

**Comment by maggia80** [comment] 2021-05-24 07:01
```
22090,471369 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.29 (right_arm-eb29-j12_15) has shown after being lost for 2.13621 sec 
22090,471378 <ERROR> hostTransceiver()::parse() detected an ERROR in sequence number from IP = 10.0.1.7. Expected: 550729, Received: 551157, Missing: 428, Prev Frame TX at 2829880356 us, This Frame TX at 2832025356 us 
22090,471387 <ERROR> hostTransceiver()::parse() detected an ERROR in sequence number from IP = 10.0.1.26. Expected: 556202, Received: 556631, Missing: 429, Prev Frame TX at 2830254767 us, This Frame TX at 2832399767 us 
22090,471396 <ERROR> hostTransceiver()::parse() detected an ERROR in sequence number from IP = 10.0.1.8. Expected: 550725, Received: 551153, Missing: 428, Prev Frame TX at 2829867983 us, This Frame TX at 2832012983 us 
22090,471406 <ERROR>  from BOARD 10.0.1.5 (torso-eb5-j0_2), src LOCAL, adr 0, time 2832s 62m 367u: (code 0x00000030, par16 0x00d5 par64 0x00000000000422d8) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471417 <ERROR> theNVmanager::Impl::ask() had a timeout for BOARD left_arm-eb26-j12_15 IP 10.0.1.26 and nv ID32 = 0x0100010b -> IND = 1, TAG = eoprot_tag_mc_joint_status_target 
22090,471426 <WARNING> EthResource::getRemoteValue() cannot have a reply from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26 at attempt # 1 w/ timeout of 0.2 seconds 
22090,471435 <ERROR>  from BOARD 10.0.1.4 (right_arm-eb4-j2_3), src LOCAL, adr 0, time 2832s 42m 736u: (code 0x00000030, par16 0x00d4 par64 0x00000000000420f6) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471447 <ERROR>   FATAL: EthResource::getRemoteValue() DID NOT have replies from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26  even after 0.200191 seconds: CANNOT PROCEED ANY FURTHER 
22090,471457 <ERROR>  from BOARD 10.0.1.8 (left_leg-eb8-j4_5), src LOCAL, adr 0, time 2832s 15m 394u: (code 0x00000030, par16 0x00d4 par64 0x0000000000042117) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471467 <ERROR> embObjMotionControl::getRefDutyCycleRaw() could not read openloop reference for  BOARD left_arm-eb26-j12_15 (IP 10.0.1.26)  joint  1 
22090,471476 <ERROR>  from BOARD 10.0.1.27 (right_arm-eb27-j4_7), src LOCAL, adr 0, time 2832s 419m 855u: (code 0x00000030, par16 0x00d4 par64 0x0000000000040fa7) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471487 <ERROR>  from BOARD 10.0.1.12 (right_leg-eb12-j4_5), src LOCAL, adr 0, time 2832s 31m 416u: (code 0x00000030, par16 0x00d4 par64 0x0000000000042df5) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471498 <ERROR>  from BOARD 10.0.1.11 (right_leg-eb11-j2_3), src LOCAL, adr 0, time 2832s 42m 709u: (code 0x00000030, par16 0x00d4 par64 0x0000000000042db7) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471508 <ERROR>  from BOARD 10.0.1.3 (right_arm-eb3-j0_1), src LOCAL, adr 0, time 2832s 38m 629u: (code 0x00000030, par16 0x00d4 par64 0x000000000004210a) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,471519 <ERROR>  from BOARD 10.0.1.10 (right_leg-eb10-j0_1), src LOCAL, adr 0, time 2832s 4m 442u: (code 0x00000030, par16 0x00d4 par64 0x0000000000042e13) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,481279 <ERROR>  from BOARD 10.0.1.7 (left_leg-eb7-j2_3), src LOCAL, adr 0, time 2832s 28m 769u: (code 0x00000030, par16 0x00d4 par64 0x000000000004210d) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,481305 <ERROR>  from BOARD 10.0.1.6 (left_leg-eb6-j0_1), src LOCAL, adr 0, time 2832s 4m 172u: (code 0x00000030, par16 0x00d4 par64 0x0000000000042117) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,481321 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.7 (left_leg-eb7-j2_3) has shown after being lost for 2.14628 sec 
22090,481335 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.8 (left_leg-eb8-j4_5) has shown after being lost for 2.1463 sec 
22090,481347 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.26 (left_arm-eb26-j12_15) has shown after being lost for 2.14633 sec 
22090,481357 <ERROR>  from BOARD 10.0.1.26 (left_arm-eb26-j12_15), src LOCAL, adr 0, time 2832s 406m 193u: (code 0x00000030, par16 0x0015 par64 0x0000000000001cc9) -> SYS: the board has detected a hole in rx ropframe sequence number. In par64 there is the expected number. The received is obtained by adding par64 with par16 treated as a int16_t + . 
22090,491334 <ERROR> hostTransceiver()::parse() detected an ERROR in sequence number from IP = 10.0.1.25. Expected: 555176, Received: 1, Missing: 18446744073708996441, Prev Frame TX at 2824863143 us, This Frame TX at 1920996 us 
22090,491359 <INFO>  from BOARD 10.0.1.25 (left_arm-eb25-j8_11), src LOCAL, adr 0, time 1s 918m 549u: (code 0x0000003b, par16 0x0000 par64 0x0000000000000000) -> SYS: the board is bootstrapping + . 
22090,491372 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.25 (left_arm-eb25-j8_11) has shown after being lost for 7.55353 sec 
22090,511517 <ERROR>  from BOARD 10.0.1.24 (left_arm-eb24-j4_7), src LOCAL, adr 0, time 2832s 425m 819u: (code 0x06000000, par16 0x0001 par64 0x3000000000000000) -> ETH monitor: link goes up in port specified by par16 (0 = ETH input (P2/P13/J4) , 1 = ETH output (P3/P12/J5) , 2 = internal). Application state is in most significant nibble of par64: 0 -> N/A, 1 -> idle, 3 -> running. + . 
22090,521606 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.25 (left_arm-eb25-j8_11) has been silent for 0.0201972 sec (its timeout is 0.02 sec) 
22090,531698 <ERROR>  from BOARD 10.0.1.26 (left_arm-eb26-j12_15), src LOCAL, adr 0, time 2832s 462m 903u: (code 0x06000000, par16 0x0000 par64 0x3000000000000000) -> ETH monitor: link goes up in port specified by par16 (0 = ETH input (P2/P13/J4) , 1 = ETH output (P3/P12/J5) , 2 = internal). Application state is in most significant nibble of par64: 0 -> N/A, 1 -> idle, 3 -> running. + . 
22090,531724 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.25 (left_arm-eb25-j8_11) has shown after being lost for 0.0252264 sec 
22090,541787 <ERROR> theNVmanager::Impl::ask() had a timeout for BOARD left_arm-eb26-j12_15 IP 10.0.1.26 and nv ID32 = 0x0100020e -> IND = 2, TAG = eoprot_tag_mc_joint_status_core_modes_ismotiondone 
22090,541815 <WARNING> EthResource::getRemoteValue() cannot have a reply from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26 at attempt # 1 w/ timeout of 0.2 seconds 
22090,541829 <ERROR>   FATAL: EthResource::getRemoteValue() DID NOT have replies from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26  even after 0.200259 seconds: CANNOT PROCEED ANY FURTHER 
22090,541840 <ERROR> Failure of askRemoteValue() inside embObjMotionControl::checkMotionDoneRaw(j= 2 ) for  BOARD left_arm-eb26-j12_15 (IP 10.0.1.26)  
22090,551881 <ERROR> theNVmanager::Impl::ask() had a timeout for BOARD left_arm-eb26-j12_15 IP 10.0.1.26 and nv ID32 = 0x0100020e -> IND = 2, TAG = eoprot_tag_mc_joint_status_core_modes_ismotiondone 
22090,551910 <WARNING> EthResource::getRemoteValue() cannot have a reply from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26 at attempt # 1 w/ timeout of 0.2 seconds 
22090,551924 <ERROR>   FATAL: EthResource::getRemoteValue() DID NOT have replies from BOARD left_arm-eb26-j12_15 with IP 10.0.1.26  even after 0.200177 seconds: CANNOT PROCEED ANY FURTHER 
22090,551934 <ERROR> Failure of askRemoteValue() inside embObjMotionControl::checkMotionDoneRaw(j= 2 ) for  BOARD left_arm-eb26-j12_15 (IP 10.0.1.26)  
22090,561983 <DEBUG> eth::EthMonitorPresence: BOARD 10.0.1.25 (left_arm-eb25-j8_11) has been silent for 0.020292 sec (its timeout is 0.02 sec) 
```

**Comment by maggia80** [comment] 2021-05-24 07:04
it seems to me somehow a congestion in the ETH bus, causing an avalanche of errors and misbehaviors

**Comment by marcoaccame** [comment] 2021-05-24 11:30
I can see a lot of CRC errors detected in the ETH communication. In thus cases, the UDP frames are not delivered and there are a lot of error messages such as: `detected an ERROR in sequence number`, `DID NOT have replies from BOARD`, `eth::EthMonitorPresence: BOARD 10.0.1.7 (left_leg-eb7-j2_3) has shown after being lost for 2.14628 sec` etc,

We must remove the CRC errors from the robot otherwise we cannot operate on it.

I am going now to map where in the robot these CRC errors happen.

It would be important to verify if the CRC errors are triggered by the grasping action or  if they are independent of that. Maybe a joint moves and sends a current leak on the robot which triggers CRC errors in ETH.

**Comment by marcoaccame** [comment] 2021-05-24 12:26
Here is what I found that surely does problems: ETH CRC errors, ETH link up and down, one board restarts. 

The CRC errors happen in boards:
- `10.0.1.10` (right_leg-eb10-j0_1), `10.0.1.11` (right_leg-eb11-j2_3) both in out port;
- `10.0.1.12` (right_leg-eb12-j4_5) in input port; (it detects the 10.0.1.11 out port)
- `10.0.1.6` (left_leg-eb6-j0_1) in output port

Also found that the ETH link goes down and then up again in following boards:
- link down in `10.0.1.24` (left_arm-eb24-j4_7), out port @ YARP time 22083,005638
  there is now a hole in the network for about 2 seconds in when no board in daisy chain after `10.0.1.24` can communicate.
- link up in `10.0.1.24` (left_arm-eb24-j4_7), out port @ YARP time 22085,105084
- link up in `10.0.1.26` (left_arm-eb26-j12_15), input port @ YARP time 22085,134987. It is the board after the `.24`.

The same pattern (`.24` link down and then up two seconds later) happens again at YARP time  22088,413366.

I can also see that board `10.0.1.25` (left_arm-eb25-j8_11) restarts at YARP time 22097,490514.

**Comment by marcoaccame** [comment] 2021-05-24 12:29
@kouroshD and @pattacini: how do we relate the time inside the log of yarplogger w/ the time reported in https://github.com/robotology/icub-tech-support/issues/1130#issuecomment-846033095?

**Comment by marcoaccame** [comment] 2021-05-24 12:55
here is my hypothesis:

- at a certain time around YARP time 22083,005638 the board `10.0.1.25` (left_arm-eb25-j8_11) has problems and ... puts its ETH link down. maybe a reset.
- the board `10.0.1.24` which is before in the ETH daisy chain detects at time 22083,005638 that its output link is down (it is the link towards the `10.0.1.25` having problems)
- two seconds later at time 22085,105084 the boards detect that the same out link is up again. That means that the  `10.0.1.25`  is now OK in terms of ETH commnication.
- at the same time, the board `10.0.1.26 `tells that its input link is also up again (the is the output link of board .25).
- at time 22097,490514 the board `10.0.1.25` transmits again and tells that ... it has just started.

So, the board `10.0.1.25` simply restarts. And after that it is certain that it stays in state `NOT CONFIGURED`.

Question now is: why does it reset and restart? I haven't enabled any restart mechanism in the FW, so if it is related to the hand grasping I would look at at some electrical noise effect or short-circuit due to uncovered cable.

**Comment by pattacini** [comment] 2021-05-24 13:38
> @kouroshD and @pattacini: how do we relate the time inside the log of yarplogger w/ the time reported in [#1130 (comment)](https://github.com/robotology/icub-tech-support/issues/1130#issuecomment-846033095)?

it depends on how @kouroshD did his acquisitions. If the system is time synched it's likely that the clock is correctly shared and the plots can refer to an absolute time baseline, although above the time origin has been clearly made equal to `0 s` for the sake of the readability, I suppose.

**Comment by kouroshD** [comment] 2021-05-24 13:48
@pattacini  @marcoaccame I used https://github.com/robotology/walking-teleoperation/blob/4be02a0abb3881ecb1a6015ee6ae6cb035b03b35/modules/HapticGlove_module/src/HapticGloveModule.cpp#L1329 yarp time to log the data. If you open the logged file with the matlab codes, you can easily find the yarp timing. Otherwise, I can tell you.

**Comment by kouroshD** [comment] 2021-05-24 13:59
For the left hand, the zero is at `1621609260.44006` and for the right hand it is the zero is `1621610324.83029`.

**Comment by marcoaccame** [comment] 2021-05-24 14:45
Ok, thanks. 

I wanted to reference the time `22083,005638` as expressed inside the log file because that is the moment in which the board restarts and then goes in `not-configured` state. But this number does not relate easily to the YARP time `1621609260.44006` you wrote, so probably the `yarplogger` uses a different timeline.

But never mind. From [here](https://github.com/robotology/icub-tech-support/issues/1130#issuecomment-846033095) we have related the grasping activity to the moment in which the board goes in `not-configured` state. And from [here](https://github.com/robotology/icub-tech-support/issues/1130#issuecomment-847023042) we found out the cause of going into `not-configured`: the board resets.

To solve the issue we need to understand why the board restarts when the hand grasps.

**Comment by kouroshD** [comment] 2021-06-04 10:00
Two videos showing how replicate the error. I suggest to try at the moment of the left hand, since there are some other problem with the right hand (refer to https://github.com/robotology/icub-tech-support/issues/1058):

https://user-images.githubusercontent.com/17707730/120784377-4d3cdf80-c52c-11eb-93d3-c79cfec18eda.mp4

**Comment by pattacini** [comment] 2021-06-04 11:51
Very nice visual explanation of the experiment @kouroshD! Thanks a lot!

We are finalizing our report on the AMO problems today (cc @marcoaccame) so that we will be dealing with this in the first days of the next week.

cc @davidetome

**Comment by pattacini** [comment] 2021-06-08 15:19
We can look at this starting tomorrow.

cc @davidetome

**Comment by davidetome** [comment] 2021-06-09 14:06
Today w/ @emilianob80 we unmounted the left forearm cover and we noticed that the boards went down.
After rebooting we tested , w/ the kind help of @kouroshD, the fingers of both hands trying to reproduce the failure both w/ the `yarpmotorgui` and teleoperation many times but the failure seems disappeared also stressing a lot the motors.

Probably the cover was stressing some wires.
Keep this issue open to see if the failure comes back.

cc @pattacini @S-Dafarra @maggia80 @Fabrizio69

**Comment by S-Dafarra** [comment] 2021-06-30 15:09
This happened also during the video shot the 23rd of June.

**Comment by DanielePucci** [comment] 2021-08-30 19:18
Probably we need further investigation on this issue?

**Comment by pattacini** [comment] 2021-08-30 20:07
Hi @DanielePucci
I told @S-Dafarra that we're awaiting feedback from you after @emilianob80 re-wired the forearms.
Before doing that, @emilianob80 spotted several wires in bad conditions, actually.

**Comment by S-Dafarra** [comment] 2021-11-02 08:46
Keeping it up for the moment.

**Comment by Uboldi80** [comment] 2021-11-22 07:35
I think this problem could be solved by the last intervention on the left hand.
@let me know @S-Dafarra if the problem persist.

**Comment by pattacini** [comment] 2021-11-24 17:15
Any feedback on this longstanding issue, @kouroshD @S-Dafarra?

**Comment by S-Dafarra** [comment] 2021-11-24 17:19
Given the amount of time spent lately to fix the arms, we avoided undergoing much stress on the hands in this period filled with demos, to be honest.

**Comment by pattacini** [comment] 2021-11-24 21:38
No problem! Keep us posted 👍🏻

**Comment by Uboldi80** [comment] 2022-02-08 08:33
following the interventions carried out and the time dedicated to the robot, this problem has arisen more

**Comment by pattacini** [comment] 2022-03-07 16:55
I think we can close this issue.
Feel free to open it up again if needed.

**Closed by pattacini** 2022-03-07 16:55 UTC
Labels: iCubGenova09
